#!/usr/bin/env bash
# setup.sh — Set up or update Claude Code agents/skills in any project
#
# Usage: ./setup.sh [target-directory]                          # Auto-detects setup vs update
#        ./setup.sh --update [target-directory]                 # Force update mode
#        ./setup.sh --compatible opencode,gemini [target-dir]   # Generate native agent files for other agents
#
# One-liner (run from your project directory):
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh)
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh) --compatible opencode,gemini

set -euo pipefail

REPO_URL="https://github.com/nickmaglowsch/claude-setup.git"
CLONE_DIR="/tmp/claude-setup"

# --- Bootstrap: ensure we're running from a full repo clone ---
# When piped via curl or run standalone without the repo files around it,
# clone the repo to /tmp and re-exec from there.
_self_bootstrap() {
  # Check if the template files exist next to this script
  local dir
  dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)" || dir=""

  # If .claude/agents/ exists next to us, we're running from the repo — nothing to do
  if [ -n "$dir" ] && [ -d "$dir/.claude/agents" ]; then
    SCRIPT_DIR="$dir"
    return
  fi

  # We're running standalone (curl pipe, downloaded copy, etc.) — need the full repo
  echo "=== Fetching claude-setup template ==="

  if [ -d "$CLONE_DIR/.git" ] && git -C "$CLONE_DIR" rev-parse --git-dir &>/dev/null; then
    echo "  Found existing clone at $CLONE_DIR, pulling latest..."
    git -C "$CLONE_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
  else
    echo "  Cloning $REPO_URL to $CLONE_DIR..."
    rm -rf "$CLONE_DIR"
    git clone --depth 1 "$REPO_URL" "$CLONE_DIR" 2>&1 | sed 's/^/  /'
  fi

  echo ""

  # Re-exec from the cloned repo, passing all original args
  exec "$CLONE_DIR/setup.sh" "$@"
}

_self_bootstrap "$@"

# --- Parse flags ---
FORCE_UPDATE=false
TARGET_DIR=""
COMPATIBLE_AGENTS=()
ADD_DEVCONTAINER=false
GLOBAL_MODE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --update|-u)
      FORCE_UPDATE=true
      shift
      ;;
    --compatible|-c)
      IFS=',' read -ra COMPATIBLE_AGENTS <<< "$2"
      shift 2
      ;;
    --add-devcontainer)
      ADD_DEVCONTAINER=true
      shift
      ;;
    --global|-g)
      GLOBAL_MODE=true
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [--update] [--compatible <agents>] [--global] [target-directory]"
      echo ""
      echo "  target-directory          Project to set up (default: current directory)"
      echo "  --update, -u              Force update mode (skip auto-detection)"
      echo "  --compatible, -c <list>   Comma-separated list of agents to generate native files for"
      echo "                            Supported: opencode, gemini"
      echo "                            Example: --compatible opencode,gemini"
      echo "  --add-devcontainer        Add devcontainer support (update mode only)"
      echo "  --global, -g              Install agents and skills into ~/.claude/ (global, not per-project)"
      echo ""
      echo "  What gets generated by --compatible:"
      echo "    opencode  →  .opencode/agents/*.md  +  AGENTS.md -> CLAUDE.md symlink"
      echo "    gemini    →  .gemini/agents/*.toml  +  GEMINI.md -> CLAUDE.md symlink"
      echo ""
      echo "  You will be prompted to choose models (heavy/standard tier) for each agent system."
      echo ""
      echo "One-liner (run from your project directory):"
      echo "  bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh)"
      exit 0
      ;;
    *)
      TARGET_DIR="$1"
      shift
      ;;
  esac
done

# Default to current directory if no target specified
if [ -z "$TARGET_DIR" ]; then
  TARGET_DIR="$(pwd)"
fi

if [ ! -d "$TARGET_DIR" ]; then
  echo "Error: '$TARGET_DIR' does not exist or is not a directory" >&2
  exit 1
fi

TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# Don't run setup on the template repo itself
if [ "$TARGET_DIR" = "$SCRIPT_DIR" ]; then
  echo "Error: Target directory is the template repo itself." >&2
  echo "Run this from your project directory, or pass the project path as an argument." >&2
  exit 1
fi

if [ "$GLOBAL_MODE" = false ]; then
  if ! git -C "$TARGET_DIR" rev-parse --git-dir &>/dev/null; then
    echo "Warning: '$TARGET_DIR' is not a git repository."
    read -rp "Continue anyway? [y/N] " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
      echo "Aborted."
      exit 0
    fi
  fi
fi

# --- Auto-detect: update if .claude/agents/ already exists, otherwise fresh setup ---
UPDATE_MODE=false
if [ "$GLOBAL_MODE" = false ]; then
  if [ "$FORCE_UPDATE" = true ]; then
    UPDATE_MODE=true
  elif [ -d "$TARGET_DIR/.claude/agents" ]; then
    echo "Existing Claude setup detected in $TARGET_DIR"
    echo ""
    UPDATE_MODE=true
  fi
fi

# --- Core template files (agents, skills, settings) ---
CLAUDE_FILES=(
  ".claude/README.md"
  ".claude/agents/app-scout.md"
  ".claude/agents/bug-fixer.md"
  ".claude/agents/bug-investigator.md"
  ".claude/agents/code-reviewer.md"
  ".claude/agents/parallel-task-orchestrator.md"
  ".claude/agents/prd-task-planner.md"
  ".claude/agents/qa-agent.md"
  ".claude/agents/refactor-planner.md"
  ".claude/agents/task-implementer.md"
  ".claude/agents/test-writer.md"
  ".claude/skills/build/SKILL.md"
  ".claude/skills/craft-pr/SKILL.md"
  ".claude/skills/debug-workflow/SKILL.md"
  ".claude/skills/init-claude-setup/SKILL.md"
  ".claude/skills/qa/SKILL.md"
  ".claude/skills/refactor/SKILL.md"
)

DEVCONTAINER_FILES=(
  ".devcontainer/Dockerfile"
  ".devcontainer/devcontainer.json"
  ".devcontainer/fix-git-worktree.sh"
  ".devcontainer/init-firewall.sh"
  ".devcontainer/README.md"
)

# --- Helper: copy file with overwrite prompt ---
copy_file() {
  local src="$1"
  local dest="$2"

  if [ -f "$dest" ]; then
    read -rp "  File exists: ${dest#"$TARGET_DIR"/} — overwrite? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
      echo "  Skipped."
      return
    fi
  fi

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  echo "  Copied: ${dest#"$TARGET_DIR"/}"
}

# --- Helper: force-copy file (no prompt) ---
force_copy_file() {
  local src="$1"
  local dest="$2"

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  echo "  Updated: ${dest#"$TARGET_DIR"/}"
}

# --- Compat helpers ---

# Returns "heavy" for agents that use opus, "standard" for sonnet-tier agents.
_agent_tier() {
  case "$1" in
    bug-investigator|code-reviewer|qa-agent) echo "heavy" ;;
    *) echo "standard" ;;
  esac
}

# Extracts the markdown body of an agent file (content after the closing --- of frontmatter).
_agent_body() {
  awk 'BEGIN{c=0} /^---/{c++; next} c>=2{print}' "$1"
}

# Extracts the first sentence of the description field from YAML frontmatter.
# Some agent files escape newlines as \\n (3 bytes) and others as \n (2 bytes);
# try the 3-byte form first so we don't clip one character too late.
_agent_desc() {
  awk '/^---/{f++; next}
       f==1 && /^description:/{
         sub(/^description: */, "")
         gsub(/^"/, "")
         idx = index($0, "\\\\n")
         if (idx == 0) idx = index($0, "\\n")
         if (idx > 0) $0 = substr($0, 1, idx-1)
         gsub(/"$/, "")
         print; exit
       }' "$1"
}

# --- Compatibility layer: generate native agent files for OpenCode and Gemini CLI ---
# Also creates AGENTS.md / GEMINI.md symlinks to CLAUDE.md for project-level context.
setup_compat_layer() {
  if [ ${#COMPATIBLE_AGENTS[@]} -eq 0 ]; then
    return
  fi

  echo "=== Compatibility layer ==="
  echo ""

  if [ ! -f "$TARGET_DIR/CLAUDE.md" ]; then
    echo "  Note: CLAUDE.md not found — create it to give all agents project-level context."
    echo ""
  fi

  for compat_agent in "${COMPATIBLE_AGENTS[@]}"; do
    case "$compat_agent" in

      opencode)
        echo "--- OpenCode ---"
        echo ""
        echo "  Heavy agents (bug-investigator, code-reviewer, qa-agent):"
        read -rp "    Model [anthropic/claude-opus-4-6]: " oc_heavy
        oc_heavy="${oc_heavy:-anthropic/claude-opus-4-6}"
        echo "  Standard agents (all others):"
        read -rp "    Model [anthropic/claude-sonnet-4-6]: " oc_standard
        oc_standard="${oc_standard:-anthropic/claude-sonnet-4-6}"
        echo ""

        local oc_dir="$TARGET_DIR/.opencode/agents"
        mkdir -p "$oc_dir"

        for agent_file in "$SCRIPT_DIR/.claude/agents/"*.md; do
          local name tier model body desc out_file
          name=$(basename "$agent_file" .md)
          tier=$(_agent_tier "$name")
          if [ "$tier" = "heavy" ]; then model="$oc_heavy"; else model="$oc_standard"; fi
          body=$(_agent_body "$agent_file")
          desc=$(_agent_desc "$agent_file")
          out_file="$oc_dir/${name}.md"

          {
            echo "---"
            echo "name: ${name}"
            printf 'description: "%s"\n' "$desc"
            echo "model: ${model}"
            echo "mode: subagent"
            echo "---"
            echo ""
            echo "$body"
          } > "$out_file"
          echo "  Generated: .opencode/agents/${name}.md  (${model})"
        done

        # AGENTS.md -> CLAUDE.md symlink for project-level context
        local agents_md="$TARGET_DIR/AGENTS.md"
        if [ -L "$agents_md" ]; then
          echo "  Already exists: AGENTS.md -> CLAUDE.md"
        elif [ ! -f "$agents_md" ]; then
          ln -s "CLAUDE.md" "$agents_md"
          echo "  Created symlink: AGENTS.md -> CLAUDE.md"
        else
          echo "  Skipped: AGENTS.md already exists (not a symlink)"
        fi
        echo ""
        ;;

      gemini)
        echo "--- Gemini CLI ---"
        echo ""
        echo "  Heavy agents (bug-investigator, code-reviewer, qa-agent):"
        read -rp "    Model [gemini-2.5-pro]: " gem_heavy
        gem_heavy="${gem_heavy:-gemini-2.5-pro}"
        echo "  Standard agents (all others):"
        read -rp "    Model [gemini-2.5-flash]: " gem_standard
        gem_standard="${gem_standard:-gemini-2.5-flash}"
        echo ""

        local gem_dir="$TARGET_DIR/.gemini/agents"
        mkdir -p "$gem_dir"

        for agent_file in "$SCRIPT_DIR/.claude/agents/"*.md; do
          local name tier model body desc out_file display_name safe_desc
          name=$(basename "$agent_file" .md)
          tier=$(_agent_tier "$name")
          if [ "$tier" = "heavy" ]; then model="$gem_heavy"; else model="$gem_standard"; fi
          body=$(_agent_body "$agent_file")
          desc=$(_agent_desc "$agent_file")
          display_name="${name//-/ }"
          safe_desc="${desc//\"/\\\"}"
          out_file="$gem_dir/${name}.toml"

          {
            echo "name = \"${name}\""
            echo "display_name = \"${display_name}\""
            echo "description = \"${safe_desc}\""
            echo "model = \"${model}\""
            echo ""
            echo "[prompts]"
            printf 'system_prompt = """\n'
            echo "$body"
            printf '"""\n'
          } > "$out_file"
          echo "  Generated: .gemini/agents/${name}.toml  (${model})"
        done

        # GEMINI.md -> CLAUDE.md symlink for project-level context
        local gemini_md="$TARGET_DIR/GEMINI.md"
        if [ -L "$gemini_md" ]; then
          echo "  Already exists: GEMINI.md -> CLAUDE.md"
        elif [ ! -f "$gemini_md" ]; then
          ln -s "CLAUDE.md" "$gemini_md"
          echo "  Created symlink: GEMINI.md -> CLAUDE.md"
        else
          echo "  Skipped: GEMINI.md already exists (not a symlink)"
        fi
        echo ""
        ;;

      *)
        echo "  Unknown agent: '$compat_agent' (supported: opencode, gemini)"
        echo ""
        ;;
    esac
  done

  echo "  Tip: commit these files so teammates using other agents benefit too."
  echo ""
}

# --- Global install: copy agents + skills into ~/.claude/ ---
perform_global_install() {
  TARGET_DIR="$HOME"
  local global_dir="$HOME/.claude"
  local is_update=false

  if [ -d "$global_dir/agents" ]; then
    is_update=true
  fi

  if [ "$is_update" = true ]; then
    echo "Updating Claude Code agents and skills globally in: $global_dir"
  else
    echo "Installing Claude Code agents and skills globally in: $global_dir"
  fi
  echo ""

  # Pull latest template
  if git -C "$SCRIPT_DIR" rev-parse --git-dir &>/dev/null; then
    echo "=== Pulling latest template ==="
    git -C "$SCRIPT_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
    echo ""
  fi

  if [ "$is_update" = true ]; then
    echo "=== Updating: agents and skills ==="
  else
    echo "=== Installing: agents and skills ==="
  fi
  echo ""

  for file in "${CLAUDE_FILES[@]}"; do
    if [ -f "$SCRIPT_DIR/$file" ]; then
      local dest="$HOME/$file"
      if [ "$is_update" = true ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$dest"
      else
        copy_file "$SCRIPT_DIR/$file" "$dest"
      fi
    fi
  done

  echo ""
  if [ "$is_update" = true ]; then
    echo "=== Global update complete! ==="
  else
    echo "=== Global install complete! ==="
  fi
  echo ""
  echo "  Agents and skills are now available globally across all your projects."
  echo "  Location: $global_dir"
  echo ""
}

# Global mode: install into ~/.claude/ and exit early (no git/project checks needed)
if [ "$GLOBAL_MODE" = true ]; then
  perform_global_install
  exit 0
fi

# ===========================================================================
# UPDATE MODE
# ===========================================================================
if [ "$UPDATE_MODE" = true ]; then
  # Verify target already has a Claude setup (relevant when --update is forced)
  if [ ! -d "$TARGET_DIR/.claude/agents" ]; then
    echo "Error: '$TARGET_DIR' does not have an existing Claude setup (.claude/agents/ not found)." >&2
    echo "Run without --update for first-time setup." >&2
    exit 1
  fi

  echo "Updating Claude Code setup in: $TARGET_DIR"
  echo ""

  # Pull latest template if this is a git repo
  if git -C "$SCRIPT_DIR" rev-parse --git-dir &>/dev/null; then
    echo "=== Pulling latest template ==="
    git -C "$SCRIPT_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
    echo ""
  else
    echo "Warning: Template directory is not a git repo, using files as-is."
    echo ""
  fi

  # Update core .claude/ files (skip settings.local.json to preserve user config)
  echo "=== Updating: .claude/ agents, skills ==="
  echo ""

  for file in "${CLAUDE_FILES[@]}"; do
    if [ -f "$SCRIPT_DIR/$file" ]; then
      force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
    fi
  done

  echo ""

  # Update devcontainer if it already exists, or install it if --add-devcontainer was passed
  if [ -d "$TARGET_DIR/.devcontainer" ]; then
    echo "=== Updating: .devcontainer/ ==="
    echo ""

    for file in "${DEVCONTAINER_FILES[@]}"; do
      if [ -f "$SCRIPT_DIR/$file" ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
      fi
    done

    chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true
    echo ""
  elif [ "$ADD_DEVCONTAINER" = true ]; then
    echo "=== Adding: .devcontainer/ ==="
    echo ""

    for file in "${DEVCONTAINER_FILES[@]}"; do
      if [ -f "$SCRIPT_DIR/$file" ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
      fi
    done

    chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true
    echo ""
  fi

  # Update run-claude.sh if it already exists in target
  if [ -f "$TARGET_DIR/run-claude.sh" ]; then
    echo "=== Updating: run-claude.sh ==="
    echo ""
    force_copy_file "$SCRIPT_DIR/run-claude.sh" "$TARGET_DIR/run-claude.sh"
    chmod +x "$TARGET_DIR/run-claude.sh" 2>/dev/null || true
    echo ""
  fi

  # Configure Playwright MCP if qa-agent is installed and not already configured
  SETTINGS_JSON="$TARGET_DIR/.claude/settings.json"
  if [ -f "$SETTINGS_JSON" ] && grep -q '"playwright"' "$SETTINGS_JSON" 2>/dev/null; then
    echo "=== Playwright MCP already configured — skipping ==="
    echo ""
  elif [ ! -f "$SETTINGS_JSON" ]; then
    echo "=== Playwright MCP (for /qa browser testing) ==="
    echo ""
    read -rp "  Add Playwright MCP for browser-based QA (/qa skill)? [y/N] " install_playwright
    echo ""
    if [[ "$install_playwright" =~ ^[Yy]$ ]]; then
      mkdir -p "$TARGET_DIR/.claude"
      cat > "$SETTINGS_JSON" <<'MCP_EOF'
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": ["@playwright/mcp@latest"]
    }
  }
}
MCP_EOF
      echo "  Created: .claude/settings.json (Playwright MCP configured)"
      echo ""
    fi
  fi

  # Ensure .gitignore has required entries
  echo "=== Updating .gitignore ==="
  echo ""

  GITIGNORE_ENTRIES=(
    ".devcontainer/.env"
    ".claude/settings.local.json"
    ".claude/auth.local.md"
    ".claude-worktrees/"
    ".DS_Store"
    "tasks/"
  )

  GITIGNORE_FILE="$TARGET_DIR/.gitignore"
  touch "$GITIGNORE_FILE"

  # Ensure file ends with a newline before appending
  if [ -s "$GITIGNORE_FILE" ] && [ "$(tail -c1 "$GITIGNORE_FILE" | wc -l)" -eq 0 ]; then
    echo "" >> "$GITIGNORE_FILE"
  fi

  # Add section comment if any entries are missing and comment doesn't exist yet
  NEEDS_SECTION=false
  for entry in "${GITIGNORE_ENTRIES[@]}"; do
    if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
      NEEDS_SECTION=true
      break
    fi
  done
  if [ "$NEEDS_SECTION" = true ] && ! grep -qxF "# .claude" "$GITIGNORE_FILE" 2>/dev/null; then
    echo "# .claude" >> "$GITIGNORE_FILE"
  fi

  for entry in "${GITIGNORE_ENTRIES[@]}"; do
    if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
      echo "$entry" >> "$GITIGNORE_FILE"
      echo "  Added to .gitignore: $entry"
    fi
  done

  echo ""

  setup_compat_layer

  echo "=== Update complete! ==="
  echo ""
  echo "  Updated template files. Your settings.local.json and agent-memory/ were preserved."
  echo "  Review the changes with: cd $TARGET_DIR && git diff"
  echo ""
  exit 0
fi

# ===========================================================================
# FIRST-TIME SETUP (original behavior)
# ===========================================================================
echo "Setting up Claude Code in: $TARGET_DIR"
echo ""

# --- Step 1: Core .claude/ files (always) ---
echo "=== Core: .claude/ agents, skills, settings ==="
echo ""

for file in "${CLAUDE_FILES[@]}"; do
  copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
done

# Create default settings.local.json if it doesn't exist
SETTINGS_FILE="$TARGET_DIR/.claude/settings.local.json"
if [ ! -f "$SETTINGS_FILE" ]; then
  mkdir -p "$TARGET_DIR/.claude"
  cat > "$SETTINGS_FILE" <<'SETTINGS_EOF'
{
  "permissions": {
    "allow": [],
    "deny": []
  }
}
SETTINGS_EOF
  echo "  Created: .claude/settings.local.json (add your permission rules here)"
else
  echo "  Kept existing: .claude/settings.local.json"
fi

echo ""

# --- Step 2: Dev container (optional) ---
read -rp "Do you want dev container support? [y/N] " install_devcontainer
echo ""

if [[ "$install_devcontainer" =~ ^[Yy]$ ]]; then
  echo "=== Dev Container: .devcontainer/ ==="
  echo ""

  for file in "${DEVCONTAINER_FILES[@]}"; do
    copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
  done

  # Make firewall script executable
  chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true

  echo ""

  # --- Step 3: Headless runner (optional, only if devcontainer selected) ---
  read -rp "Include headless runner script (run-claude.sh)? [y/N] " install_runner
  echo ""

  if [[ "$install_runner" =~ ^[Yy]$ ]]; then
    echo "=== Headless Runner: run-claude.sh ==="
    echo ""
    copy_file "$SCRIPT_DIR/run-claude.sh" "$TARGET_DIR/run-claude.sh"
    chmod +x "$TARGET_DIR/run-claude.sh" 2>/dev/null || true
    echo ""
  fi
fi

# --- Step 3b: Playwright MCP (optional) ---
SETTINGS_JSON="$TARGET_DIR/.claude/settings.json"
if [ ! -f "$SETTINGS_JSON" ]; then
  echo "=== Playwright MCP (for /qa browser testing) ==="
  echo ""
  read -rp "Add Playwright MCP for browser-based QA (/qa skill)? [y/N] " install_playwright
  echo ""
  if [[ "$install_playwright" =~ ^[Yy]$ ]]; then
    mkdir -p "$TARGET_DIR/.claude"
    cat > "$SETTINGS_JSON" <<'MCP_EOF'
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": ["@playwright/mcp@latest"]
    }
  }
}
MCP_EOF
    echo "  Created: .claude/settings.json (Playwright MCP configured)"
    echo ""
  fi
fi

# --- Step 4: Update .gitignore ---
echo "=== Updating .gitignore ==="
echo ""

GITIGNORE_ENTRIES=(
  ".devcontainer/.env"
  ".claude/settings.local.json"
  ".claude/auth.local.md"
  ".claude-worktrees/"
  ".DS_Store"
  "tasks/"
)

GITIGNORE_FILE="$TARGET_DIR/.gitignore"
touch "$GITIGNORE_FILE"

# Ensure file ends with a newline before appending
if [ -s "$GITIGNORE_FILE" ] && [ "$(tail -c1 "$GITIGNORE_FILE" | wc -l)" -eq 0 ]; then
  echo "" >> "$GITIGNORE_FILE"
fi

# Add section comment if any entries are missing and comment doesn't exist yet
NEEDS_SECTION=false
for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
    NEEDS_SECTION=true
    break
  fi
done
if [ "$NEEDS_SECTION" = true ] && ! grep -qxF "# .claude" "$GITIGNORE_FILE" 2>/dev/null; then
  echo "# .claude" >> "$GITIGNORE_FILE"
fi

for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
    echo "$entry" >> "$GITIGNORE_FILE"
    echo "  Added to .gitignore: $entry"
  else
    echo "  Already in .gitignore: $entry"
  fi
done

echo ""

# --- Step 5: Compatibility symlinks (optional, via --compatible flag) ---
setup_compat_layer

# --- Done ---
echo "=== Setup complete! ==="
echo ""
echo "Next steps:"
echo "  1. Authenticate:      claude login  (uses your Max/Pro subscription)"
echo "  2. Review .claude/settings.local.json and adjust permissions"
echo "  3. Run Claude Code:   claude"
echo ""
if [[ "${install_devcontainer:-}" =~ ^[Yy]$ ]]; then
  echo "  Dev container:"
  echo "    - VS Code: open the project, then 'Reopen in Container'"
  echo "    - Zed: open the project, you'll be prompted to launch in a container"
  echo "    - Run 'claude login' inside the container to authenticate"
  echo "    - See .devcontainer/README.md for full documentation"
  echo ""
fi
if [[ "${install_runner:-}" =~ ^[Yy]$ ]]; then
  echo "  Headless mode:"
  echo "    ./run-claude.sh --branch feature-x --prompt 'implement the feature'"
  echo ""
fi
if [[ "${install_playwright:-}" =~ ^[Yy]$ ]]; then
  echo "  Browser QA:"
  echo "    Run /qa in Claude Code with your app running to test it like a user"
  echo "    First run will auto-install @playwright/mcp via npx"
  echo ""
fi
