#!/usr/bin/env bash
# setup.sh — Set up or update Claude Code agents/skills in any project
#
# Usage: ./setup.sh                                             # Global install into ~/.claude/ (default)
#        ./setup.sh --local [target-directory]                  # Per-project install (auto-detects setup vs update)
#        ./setup.sh --update [target-directory]                 # Force update mode (local)
#        ./setup.sh --compatible opencode,gemini [target-dir]   # Generate native agent files for other agents
#
# One-liner (installs globally into ~/.claude/ by default):
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh)
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh) --local
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh) --compatible opencode,gemini

set -euo pipefail

REPO_URL="https://github.com/nickmaglowsch/claude-setup.git"
CLONE_DIR="/tmp/claude-setup"

# --- Bootstrap: ensure we're running from a full repo clone ---
# When piped via curl or run standalone without the repo files around it,
# clone the repo to /tmp and re-exec from there.
_self_bootstrap() {
  # Check if the template files exist next to this script
  local dir
  dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)" || dir=""

  # If .claude/agents/ exists next to us, we're running from the repo — nothing to do
  if [ -n "$dir" ] && [ -d "$dir/.claude/agents" ]; then
    SCRIPT_DIR="$dir"
    return
  fi

  # We're running standalone (curl pipe, downloaded copy, etc.) — need the full repo
  echo "=== Fetching claude-setup template ==="

  if [ -d "$CLONE_DIR/.git" ] && git -C "$CLONE_DIR" rev-parse --git-dir &>/dev/null; then
    echo "  Found existing clone at $CLONE_DIR, pulling latest..."
    git -C "$CLONE_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
  else
    echo "  Cloning $REPO_URL to $CLONE_DIR..."
    rm -rf "$CLONE_DIR"
    git clone --depth 1 "$REPO_URL" "$CLONE_DIR" 2>&1 | sed 's/^/  /'
  fi

  echo ""

  # Re-exec from the cloned repo, passing all original args
  exec "$CLONE_DIR/setup.sh" "$@"
}

_self_bootstrap "$@"

# --- Parse flags ---
FORCE_UPDATE=false
TARGET_DIR=""
COMPATIBLE_AGENTS=()
ADD_DEVCONTAINER=false
GLOBAL_MODE=true
TOKEN_REDUCER_ONLY=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --update|-u)
      FORCE_UPDATE=true
      shift
      ;;
    --compatible|-c)
      IFS=',' read -ra COMPATIBLE_AGENTS <<< "$2"
      shift 2
      ;;
    --add-devcontainer)
      ADD_DEVCONTAINER=true
      shift
      ;;
    --token-reducer)
      TOKEN_REDUCER_ONLY=true
      shift
      ;;
    --local|-l)
      GLOBAL_MODE=false
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [--local [target-directory]] [--update] [--compatible <agents>]"
      echo ""
      echo "  (no flags)                Global install into ~/.claude/ (default)"
      echo "  --local, -l               Per-project install into target-directory"
      echo "  target-directory          Project to set up (default: current directory, requires --local)"
      echo "  --update, -u              Force update mode (skip auto-detection, use with --local)"
      echo "  --compatible, -c <list>   Comma-separated list of agents to generate native files for"
      echo "                            Supported: opencode, gemini"
      echo "                            Example: --compatible opencode,gemini"
      echo "  --add-devcontainer        Add devcontainer support (update mode only)"
      echo "  --token-reducer           Install Token Reducer Pack only (RTK + global deny rules)"
      echo ""
      echo "  What gets generated by --compatible:"
      echo "    opencode  →  .opencode/agents/*.md  +  AGENTS.md -> CLAUDE.md symlink"
      echo "    gemini    →  .gemini/agents/*.toml  +  GEMINI.md -> CLAUDE.md symlink"
      echo ""
      echo "  You will be prompted to choose models (heavy/standard tier) for each agent system."
      echo ""
      echo "One-liner (global install by default):"
      echo "  bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh)"
      echo "  bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh) --local"
      exit 0
      ;;
    *)
      TARGET_DIR="$1"
      shift
      ;;
  esac
done

# Default to current directory if no target specified
if [ -z "$TARGET_DIR" ]; then
  TARGET_DIR="$(pwd)"
fi

if [ ! -d "$TARGET_DIR" ]; then
  echo "Error: '$TARGET_DIR' does not exist or is not a directory" >&2
  exit 1
fi

TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# Don't run setup on the template repo itself
if [ "$TARGET_DIR" = "$SCRIPT_DIR" ]; then
  echo "Error: Target directory is the template repo itself." >&2
  echo "Run this from your project directory, or pass the project path as an argument." >&2
  exit 1
fi

if [ "$GLOBAL_MODE" = false ]; then
  if ! git -C "$TARGET_DIR" rev-parse --git-dir &>/dev/null; then
    echo "Warning: '$TARGET_DIR' is not a git repository."
    read -rp "Continue anyway? [y/N] " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
      echo "Aborted."
      exit 0
    fi
  fi
fi

# --- Auto-detect: update if .claude/agents/ already exists, otherwise fresh setup ---
UPDATE_MODE=false
if [ "$GLOBAL_MODE" = false ]; then
  if [ "$FORCE_UPDATE" = true ]; then
    UPDATE_MODE=true
  elif [ -d "$TARGET_DIR/.claude/agents" ]; then
    echo "Existing Claude setup detected in $TARGET_DIR"
    echo ""
    UPDATE_MODE=true
  fi
fi

# --- Core template files (agents, skills, settings) ---
CLAUDE_FILES=(
  ".claude/README.md"
  ".claude/agents/app-scout.md"
  ".claude/agents/bug-fixer.md"
  ".claude/agents/bug-investigator.md"
  ".claude/agents/code-reviewer.md"
  ".claude/agents/parallel-task-orchestrator.md"
  ".claude/agents/prd-task-planner.md"
  ".claude/agents/qa-agent.md"
  ".claude/agents/refactor-planner.md"
  ".claude/agents/task-implementer.md"
  ".claude/agents/test-writer.md"
  ".claude/skills/build/SKILL.md"
  ".claude/skills/craft-pr/SKILL.md"
  ".claude/skills/debug-workflow/SKILL.md"
  ".claude/skills/init-claude-setup/SKILL.md"
  ".claude/skills/qa/SKILL.md"
  ".claude/skills/refactor/SKILL.md"
  ".claude/hooks/token-reducer-nudge.sh"
)

DEVCONTAINER_FILES=(
  ".devcontainer/Dockerfile"
  ".devcontainer/devcontainer.json"
  ".devcontainer/fix-git-worktree.sh"
  ".devcontainer/init-firewall.sh"
  ".devcontainer/README.md"
)

# --- Helper: copy file with overwrite prompt ---
copy_file() {
  local src="$1"
  local dest="$2"

  if [ -f "$dest" ]; then
    read -rp "  File exists: ${dest#"$TARGET_DIR"/} — overwrite? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
      echo "  Skipped."
      return
    fi
  fi

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  echo "  Copied: ${dest#"$TARGET_DIR"/}"
}

# --- Helper: force-copy file (no prompt) ---
force_copy_file() {
  local src="$1"
  local dest="$2"

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  echo "  Updated: ${dest#"$TARGET_DIR"/}"
}

# --- Compat helpers ---

# Returns "heavy" for agents that use opus, "standard" for sonnet-tier agents.
_agent_tier() {
  case "$1" in
    bug-investigator|code-reviewer|qa-agent) echo "heavy" ;;
    *) echo "standard" ;;
  esac
}

# Extracts the markdown body of an agent file (content after the closing --- of frontmatter).
_agent_body() {
  awk 'BEGIN{c=0} /^---/{c++; next} c>=2{print}' "$1"
}

# Extracts the first sentence of the description field from YAML frontmatter.
# Some agent files escape newlines as \\n (3 bytes) and others as \n (2 bytes);
# try the 3-byte form first so we don't clip one character too late.
_agent_desc() {
  awk '/^---/{f++; next}
       f==1 && /^description:/{
         sub(/^description: */, "")
         gsub(/^"/, "")
         idx = index($0, "\\\\n")
         if (idx == 0) idx = index($0, "\\n")
         if (idx > 0) $0 = substr($0, 1, idx-1)
         gsub(/"$/, "")
         print; exit
       }' "$1"
}

# --- Compatibility layer: generate native agent files for OpenCode and Gemini CLI ---
# Also creates AGENTS.md / GEMINI.md symlinks to CLAUDE.md for project-level context.
setup_compat_layer() {
  if [ ${#COMPATIBLE_AGENTS[@]} -eq 0 ]; then
    return
  fi

  echo "=== Compatibility layer ==="
  echo ""

  if [ ! -f "$TARGET_DIR/CLAUDE.md" ]; then
    echo "  Note: CLAUDE.md not found — create it to give all agents project-level context."
    echo ""
  fi

  for compat_agent in "${COMPATIBLE_AGENTS[@]}"; do
    case "$compat_agent" in

      opencode)
        echo "--- OpenCode ---"
        echo ""
        echo "  Heavy agents (bug-investigator, code-reviewer, qa-agent):"
        read -rp "    Model [anthropic/claude-opus-4-6]: " oc_heavy
        oc_heavy="${oc_heavy:-anthropic/claude-opus-4-6}"
        echo "  Standard agents (all others):"
        read -rp "    Model [anthropic/claude-sonnet-4-6]: " oc_standard
        oc_standard="${oc_standard:-anthropic/claude-sonnet-4-6}"
        echo ""

        local oc_dir="$TARGET_DIR/.opencode/agents"
        mkdir -p "$oc_dir"

        for agent_file in "$SCRIPT_DIR/.claude/agents/"*.md; do
          local name tier model body desc out_file
          name=$(basename "$agent_file" .md)
          tier=$(_agent_tier "$name")
          if [ "$tier" = "heavy" ]; then model="$oc_heavy"; else model="$oc_standard"; fi
          body=$(_agent_body "$agent_file")
          desc=$(_agent_desc "$agent_file")
          out_file="$oc_dir/${name}.md"

          {
            echo "---"
            echo "name: ${name}"
            printf 'description: "%s"\n' "$desc"
            echo "model: ${model}"
            echo "mode: subagent"
            echo "---"
            echo ""
            echo "$body"
          } > "$out_file"
          echo "  Generated: .opencode/agents/${name}.md  (${model})"
        done

        # AGENTS.md -> CLAUDE.md symlink for project-level context
        local agents_md="$TARGET_DIR/AGENTS.md"
        if [ -L "$agents_md" ]; then
          echo "  Already exists: AGENTS.md -> CLAUDE.md"
        elif [ ! -f "$agents_md" ]; then
          ln -s "CLAUDE.md" "$agents_md"
          echo "  Created symlink: AGENTS.md -> CLAUDE.md"
        else
          echo "  Skipped: AGENTS.md already exists (not a symlink)"
        fi
        echo ""
        ;;

      gemini)
        echo "--- Gemini CLI ---"
        echo ""
        echo "  Heavy agents (bug-investigator, code-reviewer, qa-agent):"
        read -rp "    Model [gemini-2.5-pro]: " gem_heavy
        gem_heavy="${gem_heavy:-gemini-2.5-pro}"
        echo "  Standard agents (all others):"
        read -rp "    Model [gemini-2.5-flash]: " gem_standard
        gem_standard="${gem_standard:-gemini-2.5-flash}"
        echo ""

        local gem_dir="$TARGET_DIR/.gemini/agents"
        mkdir -p "$gem_dir"

        for agent_file in "$SCRIPT_DIR/.claude/agents/"*.md; do
          local name tier model body desc out_file display_name safe_desc
          name=$(basename "$agent_file" .md)
          tier=$(_agent_tier "$name")
          if [ "$tier" = "heavy" ]; then model="$gem_heavy"; else model="$gem_standard"; fi
          body=$(_agent_body "$agent_file")
          desc=$(_agent_desc "$agent_file")
          display_name="${name//-/ }"
          safe_desc="${desc//\"/\\\"}"
          out_file="$gem_dir/${name}.toml"

          {
            echo "name = \"${name}\""
            echo "display_name = \"${display_name}\""
            echo "description = \"${safe_desc}\""
            echo "model = \"${model}\""
            echo ""
            echo "[prompts]"
            printf 'system_prompt = """\n'
            echo "$body"
            printf '"""\n'
          } > "$out_file"
          echo "  Generated: .gemini/agents/${name}.toml  (${model})"
        done

        # GEMINI.md -> CLAUDE.md symlink for project-level context
        local gemini_md="$TARGET_DIR/GEMINI.md"
        if [ -L "$gemini_md" ]; then
          echo "  Already exists: GEMINI.md -> CLAUDE.md"
        elif [ ! -f "$gemini_md" ]; then
          ln -s "CLAUDE.md" "$gemini_md"
          echo "  Created symlink: GEMINI.md -> CLAUDE.md"
        else
          echo "  Skipped: GEMINI.md already exists (not a symlink)"
        fi
        echo ""
        ;;

      *)
        echo "  Unknown agent: '$compat_agent' (supported: opencode, gemini)"
        echo ""
        ;;
    esac
  done

  echo "  Tip: commit these files so teammates using other agents benefit too."
  echo ""
}

# --- Auto-update: install/refresh cron job ---
_install_auto_update() {
  local script="$HOME/.claude/auto-update.sh"
  local cron_entry="*/5 * * * * bash \"$script\" >> \"$HOME/.claude/auto-update.log\" 2>&1"

  cp "$SCRIPT_DIR/auto-update.sh" "$script"
  chmod +x "$script"

  if crontab -l 2>/dev/null | grep -qF "auto-update.sh"; then
    echo "  Auto-update cron job already installed — script refreshed."
  else
    (crontab -l 2>/dev/null; echo "$cron_entry") | crontab -
    echo "  Installed cron job: checks GitHub every 5 minutes."
    # WSL: cron may need to be started manually
    if grep -qi microsoft /proc/version 2>/dev/null; then
      echo "  Note (WSL): run 'sudo service cron start' if cron is not already running."
      echo "  To start cron automatically in WSL, add it to /etc/wsl.conf or your shell profile."
    fi
  fi
}

# --- Token Reducer Pack: RTK + global deny rules ---

GLOBAL_DENY_RULES=(
  'Read(**/node_modules/**)'
  'Read(**/dist/**)'
  'Read(**/build/**)'
  'Read(**/.next/**)'
  'Read(**/.nuxt/**)'
  'Read(**/out/**)'
  'Read(**/.output/**)'
  'Read(**/*.lock)'
  'Read(**/package-lock.json)'
  'Read(**/yarn.lock)'
  'Read(**/pnpm-lock.yaml)'
  'Read(**/Cargo.lock)'
  'Read(**/Gemfile.lock)'
  'Read(**/poetry.lock)'
  'Read(**/composer.lock)'
  'Read(**/target/**)'
  'Read(**/__pycache__/**)'
  'Read(**/*.pyc)'
  'Read(**/.venv/**)'
  'Read(**/venv/**)'
  'Read(**/.gradle/**)'
  'Read(**/.m2/**)'
  'Read(**/vendor/**)'
  'Read(**/*.min.js)'
  'Read(**/*.min.css)'
  'Read(**/*.map)'
  'Read(**/*.chunk.js)'
  'Read(**/.git/**)'
  'Read(**/.DS_Store)'
  'Read(**/coverage/**)'
  'Read(**/.nyc_output/**)'
  'Read(**/logs/**)'
  'Read(**/*.log)'
)

_install_rtk() {
  local os
  os="$(uname -s)"

  # macOS: prefer brew, fallback to curl install script
  if [ "$os" = "Darwin" ]; then
    if command -v brew &>/dev/null; then
      echo "  Installing RTK via Homebrew..."
      if brew install rtk 2>&1 | sed 's/^/    /'; then
        return 0
      fi
      echo "  Homebrew install failed, trying curl installer..."
    fi
  fi

  # Linux/WSL/macOS fallback: curl install script
  echo "  Installing RTK via install script..."
  if curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh | sh 2>&1 | sed 's/^/    /'; then
    # Ensure ~/.local/bin is in PATH for current session
    if ! command -v rtk &>/dev/null; then
      export PATH="$HOME/.local/bin:$PATH"
    fi
    if command -v rtk &>/dev/null; then
      # Check if ~/.local/bin is already in shell profile
      local shell_rc="$HOME/.bashrc"
      if [ -n "${ZSH_VERSION:-}" ] || [ "$(basename "${SHELL:-}")" = "zsh" ]; then
        shell_rc="$HOME/.zshrc"
      fi
      if ! grep -q '\.local/bin' "$shell_rc" 2>/dev/null; then
        echo ""
        echo "  Note: add this to $shell_rc for permanent PATH access:"
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
      fi
      return 0
    fi
  fi

  echo "  Could not install RTK automatically."
  echo "  Install manually: https://github.com/rtk-ai/rtk#installation"
  return 1
}

_merge_global_deny_rules() {
  local settings_file="$HOME/.claude/settings.json"

  # Fast-path: already merged
  if [ -f "$settings_file" ] && grep -q 'Read(\*\*/node_modules/\*\*)' "$settings_file" 2>/dev/null; then
    echo "  Global deny rules already present — skipping."
    return 0
  fi

  mkdir -p "$HOME/.claude"

  # Build JSON array of deny rules
  local rules_json="["
  local first=true
  for rule in "${GLOBAL_DENY_RULES[@]}"; do
    if [ "$first" = true ]; then
      first=false
    else
      rules_json+=","
    fi
    rules_json+="\"$rule\""
  done
  rules_json+="]"

  if [ ! -f "$settings_file" ]; then
    # No existing file — create from scratch
    python3 -c "
import json, sys
rules = json.loads(sys.argv[1])
data = {'permissions': {'deny': rules}}
print(json.dumps(data, indent=2))
" "$rules_json" > "$settings_file" 2>/dev/null && {
      echo "  Created ~/.claude/settings.json with global deny rules."
      return 0
    }
    # python3 failed, try jq
    if command -v jq &>/dev/null; then
      echo "$rules_json" | jq '{permissions: {deny: .}}' > "$settings_file" 2>/dev/null && {
        echo "  Created ~/.claude/settings.json with global deny rules."
        return 0
      }
    fi
  else
    # Merge into existing file
    local merged
    merged=$(python3 -c "
import json, sys
rules = json.loads(sys.argv[1])
with open(sys.argv[2]) as f:
    data = json.load(f)
perms = data.setdefault('permissions', {})
existing = set(perms.get('deny', []))
perms['deny'] = perms.get('deny', []) + [r for r in rules if r not in existing]
print(json.dumps(data, indent=2))
" "$rules_json" "$settings_file" 2>/dev/null) && {
      echo "$merged" > "$settings_file"
      echo "  Merged global deny rules into ~/.claude/settings.json."
      return 0
    }
    # python3 failed, try jq
    if command -v jq &>/dev/null; then
      merged=$(jq --argjson rules "$rules_json" '
        .permissions //= {} |
        .permissions.deny //= [] |
        .permissions.deny = (.permissions.deny + ($rules - .permissions.deny))
      ' "$settings_file" 2>/dev/null) && {
        echo "$merged" > "$settings_file"
        echo "  Merged global deny rules into ~/.claude/settings.json."
        return 0
      }
    fi
  fi

  echo "  Warning: Could not merge deny rules (python3 and jq unavailable)."
  echo "  Add these rules manually to ~/.claude/settings.json:"
  echo "  https://github.com/nickmaglowsch/claude-setup#token-reducer-pack"
  return 1
}

_install_nudge_hook() {
  local hook_src="$SCRIPT_DIR/.claude/hooks/token-reducer-nudge.sh"
  local hook_dest="$HOME/.claude/hooks/token-reducer-nudge.sh"
  local settings_file="$HOME/.claude/settings.json"

  # Copy the nudge script
  mkdir -p "$HOME/.claude/hooks"
  if [ -f "$hook_src" ]; then
    cp "$hook_src" "$hook_dest"
    chmod +x "$hook_dest"
  fi

  # Register the UserPromptSubmit hook in settings.json
  if [ -f "$settings_file" ] && grep -q 'token-reducer-nudge' "$settings_file" 2>/dev/null; then
    return 0  # already registered
  fi

  mkdir -p "$HOME/.claude"

  if [ ! -f "$settings_file" ]; then
    # Create settings.json with just the hook
    cat > "$settings_file" <<'HOOK_EOF'
{
  "hooks": {
    "UserPromptSubmit": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "bash ~/.claude/hooks/token-reducer-nudge.sh"
          }
        ]
      }
    ]
  }
}
HOOK_EOF
  else
    # Merge hook into existing settings.json
    local merged
    merged=$(python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
hooks = data.setdefault('hooks', {})
ups = hooks.setdefault('UserPromptSubmit', [])
# Check if already registered
for entry in ups:
    for h in entry.get('hooks', []):
        if 'token-reducer-nudge' in h.get('command', ''):
            print(json.dumps(data, indent=2))
            sys.exit(0)
ups.append({
    'matcher': '',
    'hooks': [{'type': 'command', 'command': 'bash ~/.claude/hooks/token-reducer-nudge.sh'}]
})
print(json.dumps(data, indent=2))
" "$settings_file" 2>/dev/null) && {
      echo "$merged" > "$settings_file"
      return 0
    }
    # python3 failed, try jq
    if command -v jq &>/dev/null; then
      merged=$(jq '
        .hooks //= {} |
        .hooks.UserPromptSubmit //= [] |
        if (.hooks.UserPromptSubmit | map(.hooks[]?.command // "" | test("token-reducer-nudge")) | any)
        then .
        else .hooks.UserPromptSubmit += [{"matcher": "", "hooks": [{"type": "command", "command": "bash ~/.claude/hooks/token-reducer-nudge.sh"}]}]
        end
      ' "$settings_file" 2>/dev/null) && {
        echo "$merged" > "$settings_file"
        return 0
      }
    fi
  fi
}

_remove_nudge_hook() {
  # Remove the marker so it doesn't nudge, and clean up the hook
  touch "$HOME/.claude/.token-reducer-nudged"
}

_setup_token_reducer_pack() {
  echo "=== Token Reducer Pack ==="
  echo ""
  echo "  Reduces token usage across all projects via two mechanisms:"
  echo "  - RTK: compresses Bash tool output (60-90% token savings on CLI noise)"
  echo "  - Deny rules: blocks Claude from reading build artifacts, lock files, caches"
  echo ""
  read -rp "  Enable Token Reducer Pack? [Y/n] " enable_trp
  echo ""
  if [[ "$enable_trp" =~ ^[Nn]$ ]]; then
    # Install nudge hook so they get reminded next time they open Claude Code
    _install_nudge_hook
    return
  fi

  # Mark as installed so the nudge hook stays silent
  _remove_nudge_hook

  # --- RTK ---
  if command -v rtk &>/dev/null; then
    echo "  RTK already installed ($(rtk --version 2>/dev/null || echo 'unknown version'))."
    echo "  Refreshing Claude Code hook..."
    rtk init -g --auto-patch 2>&1 | sed 's/^/    /' || true
  else
    if _install_rtk; then
      echo "  Initializing RTK hook for Claude Code..."
      rtk init -g --auto-patch 2>&1 | sed 's/^/    /' || {
        echo "  Warning: rtk init failed. Run 'rtk init -g' manually after install."
      }
    fi
  fi
  echo ""

  # --- Global deny rules ---
  _merge_global_deny_rules
  echo ""
}

# --- Global install: copy agents + skills into ~/.claude/ ---
perform_global_install() {
  TARGET_DIR="$HOME"
  local global_dir="$HOME/.claude"
  local is_update=false

  if [ -d "$global_dir/agents" ]; then
    is_update=true
  fi

  if [ "$is_update" = true ]; then
    echo "Updating Claude Code agents and skills globally in: $global_dir"
  else
    echo "Installing Claude Code agents and skills globally in: $global_dir"
  fi
  echo ""

  # Pull latest template
  if git -C "$SCRIPT_DIR" rev-parse --git-dir &>/dev/null; then
    echo "=== Pulling latest template ==="
    git -C "$SCRIPT_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
    echo ""
  fi

  if [ "$is_update" = true ]; then
    echo "=== Updating: agents and skills ==="
  else
    echo "=== Installing: agents and skills ==="
  fi
  echo ""

  for file in "${CLAUDE_FILES[@]}"; do
    if [ -f "$SCRIPT_DIR/$file" ]; then
      local dest="$HOME/$file"
      if [ "$is_update" = true ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$dest"
      else
        copy_file "$SCRIPT_DIR/$file" "$dest"
      fi
    fi
  done

  echo ""

  # --- Auto-update ---
  local autoupdate_script="$HOME/.claude/auto-update.sh"
  if [ -f "$SCRIPT_DIR/auto-update.sh" ]; then
    local cron_installed=false
    if crontab -l 2>/dev/null | grep -qF "auto-update.sh"; then
      cron_installed=true
    fi

    if [ "$cron_installed" = true ]; then
      # Already opted in — silently refresh the script
      echo "=== Refreshing: auto-update.sh ==="
      echo ""
      _install_auto_update
      echo ""
    else
      # Not yet opted in — always ask (fresh install or existing install without cron)
      echo "=== Auto-updates ==="
      echo ""
      echo "  Checks GitHub every 5 minutes and silently applies updates when"
      echo "  a new commit lands on main. Sends a system notification when done."
      echo "  Works on macOS, Linux, and WSL. Uses cron — no extra tools needed."
      echo ""
      read -rp "  Enable auto-updates? [y/N] " enable_auto
      echo ""
      if [[ "$enable_auto" =~ ^[Yy]$ ]]; then
        _install_auto_update
        echo ""
      fi
    fi
  fi

  # --- Token Reducer Pack ---
  _setup_token_reducer_pack

  if [ "$is_update" = true ]; then
    echo "=== Global update complete! ==="
  else
    echo "=== Global install complete! ==="
  fi
  echo ""
  echo "  Agents and skills are now available globally across all your projects."
  echo "  Location: $global_dir"
  if [ -f "$autoupdate_script" ]; then
    echo "  Auto-updates: enabled (cron, every 5 min) — log: ~/.claude/auto-update.log"
    echo "  To disable: crontab -e  →  remove the line containing auto-update.sh"
  fi
  if command -v rtk &>/dev/null; then
    echo "  Token Reducer: RTK active + global deny rules in ~/.claude/settings.json"
  fi
  echo ""
}

# Token reducer only: run just the token reducer pack and exit
if [ "$TOKEN_REDUCER_ONLY" = true ]; then
  _setup_token_reducer_pack
  exit 0
fi

# Global mode: install into ~/.claude/ and exit early (no git/project checks needed)
if [ "$GLOBAL_MODE" = true ]; then
  perform_global_install
  exit 0
fi

# ===========================================================================
# UPDATE MODE
# ===========================================================================
if [ "$UPDATE_MODE" = true ]; then
  # Verify target already has a Claude setup (relevant when --update is forced)
  if [ ! -d "$TARGET_DIR/.claude/agents" ]; then
    echo "Error: '$TARGET_DIR' does not have an existing Claude setup (.claude/agents/ not found)." >&2
    echo "Run without --update for first-time setup." >&2
    exit 1
  fi

  echo "Updating Claude Code setup in: $TARGET_DIR"
  echo ""

  # Pull latest template if this is a git repo
  if git -C "$SCRIPT_DIR" rev-parse --git-dir &>/dev/null; then
    echo "=== Pulling latest template ==="
    git -C "$SCRIPT_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
    echo ""
  else
    echo "Warning: Template directory is not a git repo, using files as-is."
    echo ""
  fi

  # Update core .claude/ files (skip settings.local.json to preserve user config)
  echo "=== Updating: .claude/ agents, skills ==="
  echo ""

  for file in "${CLAUDE_FILES[@]}"; do
    if [ -f "$SCRIPT_DIR/$file" ]; then
      force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
    fi
  done

  echo ""

  # Update devcontainer if it already exists, or install it if --add-devcontainer was passed
  if [ -d "$TARGET_DIR/.devcontainer" ]; then
    echo "=== Updating: .devcontainer/ ==="
    echo ""

    for file in "${DEVCONTAINER_FILES[@]}"; do
      if [ -f "$SCRIPT_DIR/$file" ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
      fi
    done

    chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true
    echo ""
  elif [ "$ADD_DEVCONTAINER" = true ]; then
    echo "=== Adding: .devcontainer/ ==="
    echo ""

    for file in "${DEVCONTAINER_FILES[@]}"; do
      if [ -f "$SCRIPT_DIR/$file" ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
      fi
    done

    chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true
    echo ""
  fi

  # Update run-claude.sh if it already exists in target
  if [ -f "$TARGET_DIR/run-claude.sh" ]; then
    echo "=== Updating: run-claude.sh ==="
    echo ""
    force_copy_file "$SCRIPT_DIR/run-claude.sh" "$TARGET_DIR/run-claude.sh"
    chmod +x "$TARGET_DIR/run-claude.sh" 2>/dev/null || true
    echo ""
  fi

  # Configure Playwright MCP if qa-agent is installed and not already configured
  SETTINGS_JSON="$TARGET_DIR/.claude/settings.json"
  if [ -f "$SETTINGS_JSON" ] && grep -q '"playwright"' "$SETTINGS_JSON" 2>/dev/null; then
    echo "=== Playwright MCP already configured — skipping ==="
    echo ""
  elif [ ! -f "$SETTINGS_JSON" ]; then
    echo "=== Playwright MCP (for /qa browser testing) ==="
    echo ""
    read -rp "  Add Playwright MCP for browser-based QA (/qa skill)? [y/N] " install_playwright
    echo ""
    if [[ "$install_playwright" =~ ^[Yy]$ ]]; then
      mkdir -p "$TARGET_DIR/.claude"
      cat > "$SETTINGS_JSON" <<'MCP_EOF'
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": ["@playwright/mcp@latest"]
    }
  }
}
MCP_EOF
      echo "  Created: .claude/settings.json (Playwright MCP configured)"
      echo ""
    fi
  fi

  # --- Token Reducer Pack (silent refresh on update) ---
  echo "=== Refreshing: Token Reducer Pack ==="
  echo ""
  if command -v rtk &>/dev/null; then
    echo "  RTK installed — refreshing hook..."
    rtk init -g --auto-patch 2>&1 | sed 's/^/    /' || true
  fi
  _merge_global_deny_rules
  echo ""

  # Ensure .gitignore has required entries
  echo "=== Updating .gitignore ==="
  echo ""

  GITIGNORE_ENTRIES=(
    ".devcontainer/.env"
    ".claude/settings.local.json"
    ".claude/auth.local.md"
    ".claude-worktrees/"
    ".DS_Store"
    "tasks/"
    "qa-output/"
    "debug-output/"
  )

  GITIGNORE_FILE="$TARGET_DIR/.gitignore"
  touch "$GITIGNORE_FILE"

  # Ensure file ends with a newline before appending
  if [ -s "$GITIGNORE_FILE" ] && [ "$(tail -c1 "$GITIGNORE_FILE" | wc -l)" -eq 0 ]; then
    echo "" >> "$GITIGNORE_FILE"
  fi

  # Add section comment if any entries are missing and comment doesn't exist yet
  NEEDS_SECTION=false
  for entry in "${GITIGNORE_ENTRIES[@]}"; do
    if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
      NEEDS_SECTION=true
      break
    fi
  done
  if [ "$NEEDS_SECTION" = true ] && ! grep -qxF "# .claude" "$GITIGNORE_FILE" 2>/dev/null; then
    echo "# .claude" >> "$GITIGNORE_FILE"
  fi

  for entry in "${GITIGNORE_ENTRIES[@]}"; do
    if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
      echo "$entry" >> "$GITIGNORE_FILE"
      echo "  Added to .gitignore: $entry"
    fi
  done

  echo ""

  setup_compat_layer

  echo "=== Update complete! ==="
  echo ""
  echo "  Updated template files. Your settings.local.json and agent-memory/ were preserved."
  echo "  Review the changes with: cd $TARGET_DIR && git diff"
  echo ""
  exit 0
fi

# ===========================================================================
# FIRST-TIME SETUP (original behavior)
# ===========================================================================
echo "Setting up Claude Code in: $TARGET_DIR"
echo ""

# --- Step 1: Core .claude/ files (always) ---
echo "=== Core: .claude/ agents, skills, settings ==="
echo ""

for file in "${CLAUDE_FILES[@]}"; do
  copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
done

# Create default settings.local.json if it doesn't exist
SETTINGS_FILE="$TARGET_DIR/.claude/settings.local.json"
if [ ! -f "$SETTINGS_FILE" ]; then
  mkdir -p "$TARGET_DIR/.claude"
  cat > "$SETTINGS_FILE" <<'SETTINGS_EOF'
{
  "permissions": {
    "allow": [],
    "deny": []
  }
}
SETTINGS_EOF
  echo "  Created: .claude/settings.local.json (add your permission rules here)"
else
  echo "  Kept existing: .claude/settings.local.json"
fi

echo ""

# --- Step 2: Dev container (optional) ---
read -rp "Do you want dev container support? [y/N] " install_devcontainer
echo ""

if [[ "$install_devcontainer" =~ ^[Yy]$ ]]; then
  echo "=== Dev Container: .devcontainer/ ==="
  echo ""

  for file in "${DEVCONTAINER_FILES[@]}"; do
    copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
  done

  # Make firewall script executable
  chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true

  echo ""

  # --- Step 3: Headless runner (optional, only if devcontainer selected) ---
  read -rp "Include headless runner script (run-claude.sh)? [y/N] " install_runner
  echo ""

  if [[ "$install_runner" =~ ^[Yy]$ ]]; then
    echo "=== Headless Runner: run-claude.sh ==="
    echo ""
    copy_file "$SCRIPT_DIR/run-claude.sh" "$TARGET_DIR/run-claude.sh"
    chmod +x "$TARGET_DIR/run-claude.sh" 2>/dev/null || true
    echo ""
  fi
fi

# --- Step 3b: Playwright MCP (optional) ---
SETTINGS_JSON="$TARGET_DIR/.claude/settings.json"
if [ ! -f "$SETTINGS_JSON" ]; then
  echo "=== Playwright MCP (for /qa browser testing) ==="
  echo ""
  read -rp "Add Playwright MCP for browser-based QA (/qa skill)? [y/N] " install_playwright
  echo ""
  if [[ "$install_playwright" =~ ^[Yy]$ ]]; then
    mkdir -p "$TARGET_DIR/.claude"
    cat > "$SETTINGS_JSON" <<'MCP_EOF'
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": ["@playwright/mcp@latest"]
    }
  }
}
MCP_EOF
    echo "  Created: .claude/settings.json (Playwright MCP configured)"
    echo ""
  fi
fi

# --- Step 3c: Token Reducer Pack (optional) ---
_setup_token_reducer_pack

# --- Step 4: Update .gitignore ---
echo "=== Updating .gitignore ==="
echo ""

GITIGNORE_ENTRIES=(
  ".devcontainer/.env"
  ".claude/settings.local.json"
  ".claude/auth.local.md"
  ".claude-worktrees/"
  ".DS_Store"
  "tasks/"
  "qa-output/"
  "debug-output/"
)

GITIGNORE_FILE="$TARGET_DIR/.gitignore"
touch "$GITIGNORE_FILE"

# Ensure file ends with a newline before appending
if [ -s "$GITIGNORE_FILE" ] && [ "$(tail -c1 "$GITIGNORE_FILE" | wc -l)" -eq 0 ]; then
  echo "" >> "$GITIGNORE_FILE"
fi

# Add section comment if any entries are missing and comment doesn't exist yet
NEEDS_SECTION=false
for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
    NEEDS_SECTION=true
    break
  fi
done
if [ "$NEEDS_SECTION" = true ] && ! grep -qxF "# .claude" "$GITIGNORE_FILE" 2>/dev/null; then
  echo "# .claude" >> "$GITIGNORE_FILE"
fi

for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
    echo "$entry" >> "$GITIGNORE_FILE"
    echo "  Added to .gitignore: $entry"
  else
    echo "  Already in .gitignore: $entry"
  fi
done

echo ""

# --- Step 5: Compatibility symlinks (optional, via --compatible flag) ---
setup_compat_layer

# --- Done ---
echo "=== Setup complete! ==="
echo ""
echo "Next steps:"
echo "  1. Authenticate:      claude login  (uses your Max/Pro subscription)"
echo "  2. Review .claude/settings.local.json and adjust permissions"
echo "  3. Run Claude Code:   claude"
echo ""
if [[ "${install_devcontainer:-}" =~ ^[Yy]$ ]]; then
  echo "  Dev container:"
  echo "    - VS Code: open the project, then 'Reopen in Container'"
  echo "    - Zed: open the project, you'll be prompted to launch in a container"
  echo "    - Run 'claude login' inside the container to authenticate"
  echo "    - See .devcontainer/README.md for full documentation"
  echo ""
fi
if [[ "${install_runner:-}" =~ ^[Yy]$ ]]; then
  echo "  Headless mode:"
  echo "    ./run-claude.sh --branch feature-x --prompt 'implement the feature'"
  echo ""
fi
if [[ "${install_playwright:-}" =~ ^[Yy]$ ]]; then
  echo "  Browser QA:"
  echo "    Run /qa in Claude Code with your app running to test it like a user"
  echo "    First run will auto-install @playwright/mcp via npx"
  echo ""
fi
if command -v rtk &>/dev/null; then
  echo "  Token Reducer: RTK active + global deny rules in ~/.claude/settings.json"
  echo ""
fi
