#!/usr/bin/env bash
# setup.sh — Set up or update Claude Code agents/skills in any project
#
# Usage: ./setup.sh                                             # Global install into ~/.claude/ (default)
#        ./setup.sh --local [target-directory]                  # Per-project install (auto-detects setup vs update)
#        ./setup.sh --update [target-directory]                 # Force update mode (local)
#        ./setup.sh --compatible opencode,gemini,codex [target-dir] # Generate native files for other agents
#        ./setup.sh --interval 1d                               # Set auto-update interval (5m, 1h, 1d, etc.)
#
# One-liner (installs globally into ~/.claude/ by default):
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh)
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh) --local
#   bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh) --compatible opencode,gemini,codex

set -euo pipefail

REPO_URL="https://github.com/nickmaglowsch/claude-setup.git"
CLONE_DIR="/tmp/claude-setup"

# --- Bootstrap: ensure we're running from a full repo clone ---
# When piped via curl or run standalone without the repo files around it,
# clone the repo to /tmp and re-exec from there.
_self_bootstrap() {
  # Check if the template files exist next to this script
  local dir
  dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)" || dir=""

  # If .claude/agents/ exists next to us, we're running from the repo — nothing to do
  if [ -n "$dir" ] && [ -d "$dir/.claude/agents" ]; then
    SCRIPT_DIR="$dir"
    return
  fi

  # We're running standalone (curl pipe, downloaded copy, etc.) — need the full repo
  echo "=== Fetching claude-setup template ==="

  if [ -d "$CLONE_DIR/.git" ] && git -C "$CLONE_DIR" rev-parse --git-dir &>/dev/null; then
    echo "  Found existing clone at $CLONE_DIR, pulling latest..."
    git -C "$CLONE_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
  else
    echo "  Cloning $REPO_URL to $CLONE_DIR..."
    rm -rf "$CLONE_DIR"
    git clone --depth 1 "$REPO_URL" "$CLONE_DIR" 2>&1 | sed 's/^/  /'
  fi

  echo ""

  # Re-exec from the cloned repo, passing all original args
  exec "$CLONE_DIR/setup.sh" "$@"
}

_self_bootstrap "$@"

# --- Parse flags ---
FORCE_UPDATE=false
TARGET_DIR=""
COMPATIBLE_AGENTS=()
ADD_DEVCONTAINER=false
GLOBAL_MODE=true
TOKEN_REDUCER_ONLY=false
AUTO_UPDATE_INTERVAL=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --update|-u)
      FORCE_UPDATE=true
      shift
      ;;
    --compatible|-c)
      IFS=',' read -ra COMPATIBLE_AGENTS <<< "$2"
      shift 2
      ;;
    --add-devcontainer)
      ADD_DEVCONTAINER=true
      shift
      ;;
    --token-reducer)
      TOKEN_REDUCER_ONLY=true
      shift
      ;;
    --local|-l)
      GLOBAL_MODE=false
      shift
      ;;
    --interval|-i)
      if [ -z "${2:-}" ]; then
        echo "Error: --interval requires a value (e.g. 5m, 1h, 1d)" >&2
        exit 1
      fi
      AUTO_UPDATE_INTERVAL="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 [--local [target-directory]] [--update] [--compatible <agents>]"
      echo ""
      echo "  (no flags)                Global install into ~/.claude/ (default)"
      echo "  --local, -l               Per-project install into target-directory"
      echo "  target-directory          Project to set up (default: current directory, requires --local)"
      echo "  --update, -u              Force update mode (skip auto-detection, use with --local)"
      echo "  --compatible, -c <list>   Comma-separated list of agents to generate native files for"
      echo "                            Supported: opencode, gemini, codex"
      echo "                            Example: --compatible opencode,gemini,codex"
      echo "  --add-devcontainer        Add devcontainer support (update mode only)"
      echo "  --interval, -i <value>    Auto-update interval (default: 5m)"
      echo "                            Examples: 5m, 30m, 1h, 6h, 1d"
      echo "                            Change later: ./setup.sh --interval 1d"
      echo "  --token-reducer           Install Token Reducer Pack (interactive tier selection)"
      echo ""
      echo "  What gets generated by --compatible:"
      echo "    opencode  →  .opencode/agents/*.md  +  AGENTS.md -> CLAUDE.md symlink"
      echo "    gemini    →  .gemini/agents/*.toml  +  GEMINI.md -> CLAUDE.md symlink"
      echo "    codex     →  ~/plugins/claude-setup-codex/ + ~/.agents/plugins/marketplace.json"
      echo ""
      echo "  You will be prompted to choose models (heavy/standard tier) for each agent system."
      echo ""
      echo "One-liner (global install by default):"
      echo "  bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh)"
      echo "  bash <(curl -fsSL https://raw.githubusercontent.com/nickmaglowsch/claude-setup/main/setup.sh) --local"
      exit 0
      ;;
    *)
      TARGET_DIR="$1"
      shift
      ;;
  esac
done

# Default to current directory if no target specified
if [ -z "$TARGET_DIR" ]; then
  TARGET_DIR="$(pwd)"
fi

if [ ! -d "$TARGET_DIR" ]; then
  echo "Error: '$TARGET_DIR' does not exist or is not a directory" >&2
  exit 1
fi

TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# Don't run setup on the template repo itself
if [ "$TARGET_DIR" = "$SCRIPT_DIR" ]; then
  echo "Error: Target directory is the template repo itself." >&2
  echo "Run this from your project directory, or pass the project path as an argument." >&2
  exit 1
fi

if [ "$GLOBAL_MODE" = false ]; then
  if ! git -C "$TARGET_DIR" rev-parse --git-dir &>/dev/null; then
    echo "Warning: '$TARGET_DIR' is not a git repository."
    read -rp "Continue anyway? [y/N] " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
      echo "Aborted."
      exit 0
    fi
  fi
fi

# --- Auto-detect: update if .claude/agents/ already exists, otherwise fresh setup ---
UPDATE_MODE=false
if [ "$GLOBAL_MODE" = false ]; then
  if [ "$FORCE_UPDATE" = true ]; then
    UPDATE_MODE=true
  elif [ -d "$TARGET_DIR/.claude/agents" ]; then
    echo "Existing Claude setup detected in $TARGET_DIR"
    echo ""
    UPDATE_MODE=true
  fi
fi

# --- Core template files (agents, skills, settings) ---
CLAUDE_FILES=(
  ".claude/README.md"
  ".claude/agents/agent-teams-orchestrator.md"
  ".claude/agents/app-scout.md"
  ".claude/agents/bug-fixer.md"
  ".claude/agents/bug-investigator.md"
  ".claude/agents/code-reviewer.md"
  ".claude/agents/parallel-task-orchestrator.md"
  ".claude/agents/prd-task-planner.md"
  ".claude/agents/qa-agent.md"
  ".claude/agents/refactor-planner.md"
  ".claude/agents/task-implementer.md"
  ".claude/agents/tdd-mode.md"
  ".claude/agents/test-writer.md"
  ".claude/skills/build/SKILL.md"
  ".claude/skills/craft-pr/SKILL.md"
  ".claude/skills/debug-workflow/SKILL.md"
  ".claude/skills/grill-me/SKILL.md"
  ".claude/skills/grill-with-docs/SKILL.md"
  ".claude/skills/grill-with-docs/CONTEXT-FORMAT.md"
  ".claude/skills/grill-with-docs/ADR-FORMAT.md"
  ".claude/skills/init-claude-setup/SKILL.md"
  ".claude/skills/qa/SKILL.md"
  ".claude/skills/refactor/SKILL.md"
  ".claude/hooks/token-reducer-nudge.sh"
  ".claude/statusline.sh"
)

DEVCONTAINER_FILES=(
  ".devcontainer/Dockerfile"
  ".devcontainer/devcontainer.json"
  ".devcontainer/fix-git-worktree.sh"
  ".devcontainer/init-firewall.sh"
  ".devcontainer/README.md"
)

# --- Helper: copy file with overwrite prompt ---
copy_file() {
  local src="$1"
  local dest="$2"

  if [ -f "$dest" ]; then
    read -rp "  File exists: ${dest#"$TARGET_DIR"/} — overwrite? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
      echo "  Skipped."
      return
    fi
  fi

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  echo "  Copied: ${dest#"$TARGET_DIR"/}"
}

# --- Helper: force-copy file (no prompt) ---
force_copy_file() {
  local src="$1"
  local dest="$2"

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  echo "  Updated: ${dest#"$TARGET_DIR"/}"
}

# --- Compat helpers ---

# Returns "heavy" for agents that use opus, "standard" for sonnet-tier agents.
_agent_tier() {
  case "$1" in
    bug-investigator|code-reviewer|qa-agent) echo "heavy" ;;
    *) echo "standard" ;;
  esac
}

# Extracts the markdown body of an agent file (content after the closing --- of frontmatter).
_agent_body() {
  awk 'BEGIN{c=0} /^---/{c++; next} c>=2{print}' "$1"
}

# Extracts the first sentence of the description field from YAML frontmatter.
# Some agent files escape newlines as \\n (3 bytes) and others as \n (2 bytes);
# try the 3-byte form first so we don't clip one character too late.
_agent_desc() {
  awk '/^---/{f++; next}
       f==1 && /^description:/{
         sub(/^description: */, "")
         gsub(/^"/, "")
         idx = index($0, "\\\\n")
         if (idx == 0) idx = index($0, "\\n")
         if (idx > 0) $0 = substr($0, 1, idx-1)
         gsub(/"$/, "")
         print; exit
       }' "$1"
}

# --- Codex plugin compatibility helpers ---

_setup_codex_plugin() {
  local plugin_name="claude-setup-codex"
  local plugin_dir="$HOME/plugins/$plugin_name"
  local marketplace_file="$HOME/.agents/plugins/marketplace.json"

  echo "--- Codex CLI ---"
  echo ""
  echo "  Generating home-local Codex plugin:"
  echo "    $plugin_dir"

  if ! command -v python3 >/dev/null 2>&1; then
    echo "  Error: python3 is required but not installed; please install Python 3" >&2
    return 1
  fi

  SCRIPT_DIR="$SCRIPT_DIR" PLUGIN_DIR="$plugin_dir" MARKETPLACE_FILE="$marketplace_file" python3 <<'PY'
import json
import os
import re
import shutil
import sys
import traceback
from pathlib import Path

plugin_name = "claude-setup-codex"

fallback_skills = [
    "build",
    "debug-workflow",
    "refactor",
    "qa",
    "craft-pr",
    "grill-me",
    "grill-with-docs",
    "init-claude-setup",
]

fallback_agent_ref_names = [
    "app-scout",
    "bug-fixer",
    "bug-investigator",
    "code-reviewer",
    "parallel-task-orchestrator",
    "prd-task-planner",
    "qa-agent",
    "refactor-planner",
    "task-implementer",
    "tdd-mode",
    "test-writer",
]

def warn(function_name: str, pattern: str) -> None:
    print(
        f"Warning: {function_name} made no substitutions for pattern: {pattern}",
        file=sys.stderr,
    )

def discover_skills(script_dir: Path) -> list[str]:
    skills_dir = script_dir / ".claude" / "skills"
    if not skills_dir.is_dir():
        return fallback_skills
    discovered = sorted(
        {
            path.name.strip()
            for path in skills_dir.iterdir()
            if path.is_dir() and (path / "SKILL.md").is_file() and path.name.strip()
        }
    )
    return discovered or fallback_skills

def discover_agent_refs(script_dir: Path) -> list[str]:
    agents_dir = script_dir / ".claude" / "agents"
    if not agents_dir.is_dir():
        return fallback_agent_ref_names
    discovered = sorted(
        {
            path.stem.strip()
            for path in agents_dir.glob("*.md")
            if path.is_file() and path.stem.strip() != "agent-teams-orchestrator"
        }
    )
    return discovered or fallback_agent_ref_names

def strip_agent_teams_sections(text: str) -> str:
    pattern = r"\n## Step 0\.2: Orchestration Mode Selection\n.*?(?=\n## Step 0:)"
    text, count = re.subn(
        pattern,
        "\n## Step 0.2: Orchestration Mode\n\nUse Codex's default delegation model. Set `ORCHESTRATION_MODE=parallel` for the rest of this workflow. The Claude-only team mode is intentionally not converted in this v1 plugin.\n",
        text,
        flags=re.S,
    )
    if count == 0 and "Orchestration Mode Selection" in text:
        warn("strip_agent_teams_sections", pattern)

    pattern = r"\nCheck for a saved orchestration mode preference:\n.*?(?=\n## Step 0:)"
    text, count = re.subn(
        pattern,
        "\nUse Codex's default delegation model. Set `ORCHESTRATION_MODE=parallel` for the rest of this workflow. The Claude-only team mode is intentionally not converted in this v1 plugin.\n\n",
        text,
        flags=re.S,
    )
    if count == 0 and "Check for a saved orchestration mode preference" in text:
        warn("strip_agent_teams_sections", pattern)

    pattern = r"\nIf `ORCHESTRATION_MODE=agent-teams`:.*?\n\n"
    text, count = re.subn(
        pattern,
        "\n",
        text,
        flags=re.S,
    )
    if count == 0 and "`ORCHESTRATION_MODE=agent-teams`" in text:
        warn("strip_agent_teams_sections", pattern)

    pattern = r"\n\*\*If `ORCHESTRATION_MODE=agent-teams`\*\*.*?(?=\n## Step 2b:)"
    text, count = re.subn(
        pattern,
        "\n",
        text,
        flags=re.S,
    )
    if count == 0 and "**If `ORCHESTRATION_MODE=agent-teams`**" in text:
        warn("strip_agent_teams_sections", pattern)
    return text

def convert_common(text: str, *, is_skill: bool) -> str:
    text = strip_agent_teams_sections(text)
    replacements = {
        "AskUserQuestion": "direct user questioning",
        "Task tool": "Codex delegation",
        "Task-tool": "Codex delegation",
        "sub-agent approach": "Codex delegation approach",
        "sub-agent": "delegated agent",
        "sub-agents": "delegated agents",
        "Claude Code's native": "Claude-specific",
        "Claude Code": "Codex",
        ".claude/app-context.md": ".codex/app-context.md",
        ".claude/auth.local.md": ".codex/auth.local.md",
        ".claude/agent-memory": ".codex/agent-memory",
        "~/.claude/agents/": "this plugin's `references/agents/`",
        ".claude/agents/": "this plugin's `references/agents/`",
        "~/.claude/": "~/.codex/",
    }
    for old, new in replacements.items():
        if old in text:
            text = text.replace(old, new)

    pattern = r"- `subagent_type: \"([^\"]+)\"`"
    text, count = re.subn(
        pattern,
        lambda m: f"- Codex helper prompt: `references/agents/{m.group(1)}.md`",
        text,
    )
    if count == 0 and "subagent_type" in text:
        warn("convert_common", pattern)

    pattern = r"Launch(?: the)? `([^`]+)` (?:agent )?with `subagent_type: \"([^\"]+)\"`"
    text, count = re.subn(
        pattern,
        lambda m: f"Delegate to `{m.group(2)}` using `references/agents/{m.group(2)}.md`",
        text,
    )
    if count == 0 and "Launch" in text and "subagent_type" in text:
        warn("convert_common", pattern)

    pattern = r"with `subagent_type: \"([^\"]+)\"`"
    text, count = re.subn(
        pattern,
        lambda m: f"using Codex delegation with `references/agents/{m.group(1)}.md`",
        text,
    )
    if count == 0 and "subagent_type" in text:
        warn("convert_common", pattern)

    pattern = r"`subagent_type: \"([^\"]+)\"`"
    text, count = re.subn(
        pattern,
        lambda m: f"`references/agents/{m.group(1)}.md`",
        text,
    )
    if count == 0 and "subagent_type" in text:
        warn("convert_common", pattern)
    if "subagent_type" in text:
        warn("convert_common", "remaining subagent_type text")
    text = text.replace("ORCHESTRATION_MODE=agent-teams", "ORCHESTRATION_MODE=parallel")
    text = text.replace("agent-teams", "parallel")
    text = text.replace("Agent Teams", "Claude-only team mode")
    text = text.replace("CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS", "CLAUDE_ONLY_TEAM_MODE_DISABLED")
    text = text.replace("CLAUDE.md", "CLAUDE.md / AGENTS.md")
    if is_skill:
        note = (
            "\n## Codex Compatibility\n\n"
            "This skill is generated from the canonical Claude setup source. In Codex, ask the user directly when a step calls for interaction, and use `references/agents/*.md` as prompt references when delegating specialized work. Codex reads `AGENTS.md` for project instructions; if a project only has `CLAUDE.md`, create an `AGENTS.md` symlink to it before relying on shared project guidance.\n\n"
        )
        text = re.sub(r"(---\n\n# [^\n]+\n)", r"\1" + note, text, count=1)
    return text

def init_codex_skill() -> str:
    return """---
name: init-claude-setup
description: "Initialize project-level compatibility files for Codex when using the claude-setup-codex plugin."
argument-hint: ""
---

# Init Claude Setup For Codex

Initialize project-level Codex compatibility without copying the canonical Claude agents or skills.

## Steps

1. If `AGENTS.md` does not exist and `CLAUDE.md` exists, create an `AGENTS.md -> CLAUDE.md` symlink so Codex reads the shared project instructions.
2. Ensure `.gitignore` contains these generated artifact entries, adding only missing lines under a `# codex claude-setup compatibility` section:

```gitignore
tasks/**
qa-output/**
debug-output/
.codex/app-context.md
.codex/auth.local.md
.codex/agent-memory/
.claude-worktrees/
.playwright-cli/
```

3. Create `.codex/` only when one of the Codex-local files above is needed. Do not overwrite existing files.
4. Summarize what changed and what was already up to date.

## Rules

- Never remove existing `.gitignore` entries.
- Never overwrite an existing `AGENTS.md`.
- Keep Claude setup canonical; this skill only adds Codex-readable project compatibility.
"""

def main() -> None:
    script_dir = Path(os.environ["SCRIPT_DIR"])
    plugin_dir = Path(os.environ["PLUGIN_DIR"]).expanduser()
    marketplace_file = Path(os.environ["MARKETPLACE_FILE"]).expanduser()
    skills = discover_skills(script_dir)
    agent_ref_names = discover_agent_refs(script_dir)

    plugin_dir.mkdir(parents=True, exist_ok=True)
    (plugin_dir / ".codex-plugin").mkdir(parents=True, exist_ok=True)
    (plugin_dir / "skills").mkdir(parents=True, exist_ok=True)
    (plugin_dir / "references" / "agents").mkdir(parents=True, exist_ok=True)

    manifest = {
        "name": plugin_name,
        "version": "0.1.0",
        "description": "Codex-compatible skills generated from nickmaglowsch/claude-setup.",
        "author": {
            "name": "Nick Maglowsch",
            "url": "https://github.com/nickmaglowsch",
        },
        "homepage": "https://github.com/nickmaglowsch/claude-setup",
        "repository": "https://github.com/nickmaglowsch/claude-setup",
        "license": "MIT",
        "keywords": ["codex", "skills", "claude-setup", "software-development"],
        "skills": "./skills/",
        "interface": {
            "displayName": "Claude Setup for Codex",
            "shortDescription": "Codex skills generated from claude-setup workflows.",
            "longDescription": (
                "Home-local Codex plugin containing converted build, debug, refactor, QA, "
                "PR, and grilling workflows. Claude setup remains the canonical source."
            ),
            "developerName": "Nick Maglowsch",
            "category": "Productivity",
            "capabilities": ["Interactive", "Write"],
            "websiteURL": "https://github.com/nickmaglowsch/claude-setup",
            "defaultPrompt": [
                "Use the build skill to implement this PRD.",
                "Run the debug workflow for this bug.",
                "QA this running app like a user.",
            ],
            "brandColor": "#10A37F",
        },
    }
    (plugin_dir / ".codex-plugin" / "plugin.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )

    for skill in skills:
        src_dir = script_dir / ".claude" / "skills" / skill
        out_dir = plugin_dir / "skills" / skill
        out_dir.mkdir(parents=True, exist_ok=True)
        if skill == "init-claude-setup":
            body = init_codex_skill()
        else:
            body = (src_dir / "SKILL.md").read_text(encoding="utf-8")
            body = convert_common(body, is_skill=True)
        (out_dir / "SKILL.md").write_text(body, encoding="utf-8")
        for extra in src_dir.iterdir():
            if extra.is_file() and extra.name != "SKILL.md":
                shutil.copy2(extra, out_dir / extra.name)

    for name in agent_ref_names:
        src = script_dir / ".claude" / "agents" / f"{name}.md"
        if src.exists():
            body = convert_common(src.read_text(encoding="utf-8"), is_skill=False)
            (plugin_dir / "references" / "agents" / f"{name}.md").write_text(body, encoding="utf-8")

    marketplace_file.parent.mkdir(parents=True, exist_ok=True)
    if marketplace_file.exists():
        data = json.loads(marketplace_file.read_text(encoding="utf-8"))
    else:
        data = {
            "name": "local",
            "interface": {"displayName": "Local Plugins"},
            "plugins": [],
        }
    data.setdefault("name", "local")
    data.setdefault("interface", {}).setdefault("displayName", "Local Plugins")
    plugins = data.setdefault("plugins", [])
    entry = {
        "name": plugin_name,
        "source": {
            "source": "local",
            "path": f"./plugins/{plugin_name}",
        },
        "policy": {
            "installation": "AVAILABLE",
            "authentication": "ON_INSTALL",
        },
        "category": "Productivity",
    }
    plugins[:] = [p for p in plugins if p.get("name") != plugin_name]
    plugins.append(entry)
    marketplace_file.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

try:
    main()
except Exception as exc:
    print(f"Error: failed to generate Codex plugin: {exc}", file=sys.stderr)
    print(traceback.format_exc(), file=sys.stderr)
    sys.exit(1)
PY

  echo "  Generated: ~/plugins/$plugin_name/.codex-plugin/plugin.json"
  echo "  Generated: ~/plugins/$plugin_name/skills/*/SKILL.md"
  echo "  Generated: ~/plugins/$plugin_name/references/agents/*.md"
  echo "  Updated: ~/.agents/plugins/marketplace.json"

  if [ -f "$TARGET_DIR/CLAUDE.md" ] && [ ! -e "$TARGET_DIR/AGENTS.md" ]; then
    ln -s "CLAUDE.md" "$TARGET_DIR/AGENTS.md"
    echo "  Created symlink: AGENTS.md -> CLAUDE.md"
  elif [ -e "$TARGET_DIR/AGENTS.md" ]; then
    echo "  AGENTS.md already exists — leaving it unchanged"
  fi
  echo ""
}

# --- Compatibility layer: generate native files for OpenCode, Gemini CLI, and Codex CLI ---
# Also creates AGENTS.md / GEMINI.md symlinks to CLAUDE.md for project-level context.
setup_compat_layer() {
  if [ ${#COMPATIBLE_AGENTS[@]} -eq 0 ]; then
    return
  fi

  echo "=== Compatibility layer ==="
  echo ""

  if [ ! -f "$TARGET_DIR/CLAUDE.md" ]; then
    echo "  Note: CLAUDE.md not found — create it to give all agents project-level context."
    echo ""
  fi

  for compat_agent in "${COMPATIBLE_AGENTS[@]}"; do
    case "$compat_agent" in

      opencode)
        echo "--- OpenCode ---"
        echo ""
        echo "  Heavy agents (bug-investigator, code-reviewer, qa-agent):"
        read -rp "    Model [anthropic/claude-opus-4-6]: " oc_heavy
        oc_heavy="${oc_heavy:-anthropic/claude-opus-4-6}"
        echo "  Standard agents (all others):"
        read -rp "    Model [anthropic/claude-sonnet-4-6]: " oc_standard
        oc_standard="${oc_standard:-anthropic/claude-sonnet-4-6}"
        echo ""

        local oc_dir="$TARGET_DIR/.opencode/agents"
        mkdir -p "$oc_dir"

        for agent_file in "$SCRIPT_DIR/.claude/agents/"*.md; do
          local name tier model body desc out_file
          name=$(basename "$agent_file" .md)
          tier=$(_agent_tier "$name")
          if [ "$tier" = "heavy" ]; then model="$oc_heavy"; else model="$oc_standard"; fi
          body=$(_agent_body "$agent_file")
          desc=$(_agent_desc "$agent_file")
          out_file="$oc_dir/${name}.md"

          {
            echo "---"
            echo "name: ${name}"
            printf 'description: "%s"\n' "$desc"
            echo "model: ${model}"
            echo "mode: subagent"
            echo "---"
            echo ""
            echo "$body"
          } > "$out_file"
          echo "  Generated: .opencode/agents/${name}.md  (${model})"
        done

        # AGENTS.md -> CLAUDE.md symlink for project-level context
        local agents_md="$TARGET_DIR/AGENTS.md"
        if [ -L "$agents_md" ]; then
          echo "  Already exists: AGENTS.md -> CLAUDE.md"
        elif [ ! -f "$agents_md" ]; then
          ln -s "CLAUDE.md" "$agents_md"
          echo "  Created symlink: AGENTS.md -> CLAUDE.md"
        else
          echo "  Skipped: AGENTS.md already exists (not a symlink)"
        fi
        echo ""
        ;;

      gemini)
        echo "--- Gemini CLI ---"
        echo ""
        echo "  Heavy agents (bug-investigator, code-reviewer, qa-agent):"
        read -rp "    Model [gemini-2.5-pro]: " gem_heavy
        gem_heavy="${gem_heavy:-gemini-2.5-pro}"
        echo "  Standard agents (all others):"
        read -rp "    Model [gemini-2.5-flash]: " gem_standard
        gem_standard="${gem_standard:-gemini-2.5-flash}"
        echo ""

        local gem_dir="$TARGET_DIR/.gemini/agents"
        mkdir -p "$gem_dir"

        for agent_file in "$SCRIPT_DIR/.claude/agents/"*.md; do
          local name tier model body desc out_file display_name safe_desc
          name=$(basename "$agent_file" .md)
          tier=$(_agent_tier "$name")
          if [ "$tier" = "heavy" ]; then model="$gem_heavy"; else model="$gem_standard"; fi
          body=$(_agent_body "$agent_file")
          desc=$(_agent_desc "$agent_file")
          display_name="${name//-/ }"
          safe_desc="${desc//\"/\\\"}"
          out_file="$gem_dir/${name}.toml"

          {
            echo "name = \"${name}\""
            echo "display_name = \"${display_name}\""
            echo "description = \"${safe_desc}\""
            echo "model = \"${model}\""
            echo ""
            echo "[prompts]"
            printf 'system_prompt = """\n'
            echo "$body"
            printf '"""\n'
          } > "$out_file"
          echo "  Generated: .gemini/agents/${name}.toml  (${model})"
        done

        # GEMINI.md -> CLAUDE.md symlink for project-level context
        local gemini_md="$TARGET_DIR/GEMINI.md"
        if [ -L "$gemini_md" ]; then
          echo "  Already exists: GEMINI.md -> CLAUDE.md"
        elif [ ! -f "$gemini_md" ]; then
          ln -s "CLAUDE.md" "$gemini_md"
          echo "  Created symlink: GEMINI.md -> CLAUDE.md"
        else
          echo "  Skipped: GEMINI.md already exists (not a symlink)"
        fi
        echo ""
        ;;

      codex)
        _setup_codex_plugin
        ;;

      *)
        echo "  Unknown agent: '$compat_agent' (supported: opencode, gemini, codex)"
        echo ""
        ;;
    esac
  done

  echo "  Tip: commit these files so teammates using other agents benefit too."
  echo ""
}

# --- Auto-update interval config ---
AUTO_UPDATE_CONF="$HOME/.claude/auto-update.conf"

# Convert a human-friendly interval (5m, 30m, 1h, 6h, 1d) to a cron schedule.
_interval_to_cron() {
  local interval="$1"
  local num="${interval%[mhdMHD]}"
  local unit="${interval##*[0-9]}"
  unit=$(echo "$unit" | tr '[:upper:]' '[:lower:]')

  if ! [[ "$num" =~ ^[0-9]+$ ]] || [ "$num" -lt 1 ]; then
    echo ""
    return
  fi

  case "$unit" in
    m)
      if [ "$num" -ge 60 ]; then
        echo ""
      else
        echo "*/$num * * * *"
      fi
      ;;
    h)
      if [ "$num" -ge 24 ]; then
        echo ""
      elif [ "$num" -eq 1 ]; then
        echo "0 * * * *"
      else
        echo "0 */$num * * *"
      fi
      ;;
    d)
      # cron "*/N" for days-of-month resets at month boundaries, so only "1d" is reliable
      if [ "$num" -eq 1 ]; then
        echo "0 0 * * *"
      else
        echo ""
      fi
      ;;
    *)
      echo ""
      ;;
  esac
}

# Human-readable label for an interval value.
_interval_label() {
  local interval="$1"
  local num="${interval%[mhdMHD]}"
  local unit="${interval##*[0-9]}"
  unit=$(echo "$unit" | tr '[:upper:]' '[:lower:]')

  case "$unit" in
    m)
      if [ "$num" -eq 1 ]; then echo "every minute"
      else echo "every ${num} minutes"; fi ;;
    h)
      if [ "$num" -eq 1 ]; then echo "every hour"
      else echo "every ${num} hours"; fi ;;
    d) echo "daily" ;;
    *) echo "$interval" ;;
  esac
}

# Read the persisted interval, defaulting to 5m.
_get_auto_update_interval() {
  if [ -n "$AUTO_UPDATE_INTERVAL" ]; then
    echo "$AUTO_UPDATE_INTERVAL"
  elif [ -f "$AUTO_UPDATE_CONF" ]; then
    local saved
    saved=$(grep -E '^interval=' "$AUTO_UPDATE_CONF" 2>/dev/null | head -1 | cut -d= -f2)
    echo "${saved:-5m}"
  else
    echo "5m"
  fi
}

# Persist the interval to the config file.
_save_auto_update_interval() {
  local interval="$1"
  mkdir -p "$(dirname "$AUTO_UPDATE_CONF")"
  echo "interval=$interval" > "$AUTO_UPDATE_CONF"
}

# --- Auto-update: install/refresh cron job ---
_install_auto_update() {
  local script="$HOME/.claude/auto-update.sh"
  local interval
  interval=$(_get_auto_update_interval)
  local cron_schedule
  cron_schedule=$(_interval_to_cron "$interval")

  if [ -z "$cron_schedule" ]; then
    echo "  Error: invalid interval '$interval'. Use examples like 5m, 30m, 1h, 6h, 1d." >&2
    return 1
  fi

  local cron_entry="$cron_schedule bash \"$script\" >> \"$HOME/.claude/auto-update.log\" 2>&1"

  cp "$SCRIPT_DIR/auto-update.sh" "$script"
  chmod +x "$script"

  # Remove any existing auto-update cron entry before adding the new one
  local existing_crontab
  existing_crontab=$(crontab -l 2>/dev/null | grep -vF "auto-update.sh" || true)
  if [ -n "$existing_crontab" ]; then
    (echo "$existing_crontab"; echo "$cron_entry") | crontab -
  else
    echo "$cron_entry" | crontab -
  fi

  _save_auto_update_interval "$interval"
  echo "  Installed cron job: checks $(_interval_label "$interval")."
  # WSL: cron may need to be started manually
  if grep -qi microsoft /proc/version 2>/dev/null; then
    echo "  Note (WSL): run 'sudo service cron start' if cron is not already running."
    echo "  To start cron automatically in WSL, add it to /etc/wsl.conf or your shell profile."
  fi
}

# --- Token Reducer Pack: RTK + global deny rules ---

GLOBAL_DENY_RULES=(
  'Read(**/node_modules/**)'
  'Read(**/dist/**)'
  'Read(**/build/**)'
  'Read(**/.next/**)'
  'Read(**/.nuxt/**)'
  'Read(**/out/**)'
  'Read(**/.output/**)'
  'Read(**/*.lock)'
  'Read(**/package-lock.json)'
  'Read(**/yarn.lock)'
  'Read(**/pnpm-lock.yaml)'
  'Read(**/Cargo.lock)'
  'Read(**/Gemfile.lock)'
  'Read(**/poetry.lock)'
  'Read(**/composer.lock)'
  'Read(**/target/**)'
  'Read(**/__pycache__/**)'
  'Read(**/*.pyc)'
  'Read(**/.venv/**)'
  'Read(**/venv/**)'
  'Read(**/.gradle/**)'
  'Read(**/.m2/**)'
  'Read(**/vendor/**)'
  'Read(**/*.min.js)'
  'Read(**/*.min.css)'
  'Read(**/*.map)'
  'Read(**/*.chunk.js)'
  'Read(**/.git/**)'
  'Read(**/.DS_Store)'
  'Read(**/coverage/**)'
  'Read(**/.nyc_output/**)'
  'Read(**/logs/**)'
  'Read(**/*.log)'
)

_install_rtk() {
  local os
  os="$(uname -s)"

  # macOS: prefer brew, fallback to curl install script
  if [ "$os" = "Darwin" ]; then
    if command -v brew &>/dev/null; then
      echo "  Installing RTK via Homebrew..."
      if brew install rtk 2>&1 | sed 's/^/    /'; then
        return 0
      fi
      echo "  Homebrew install failed, trying curl installer..."
    fi
  fi

  # Linux/WSL/macOS fallback: curl install script
  echo "  Installing RTK via install script..."
  if curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh | sh 2>&1 | sed 's/^/    /'; then
    # Ensure ~/.local/bin is in PATH for current session
    if ! command -v rtk &>/dev/null; then
      export PATH="$HOME/.local/bin:$PATH"
    fi
    if command -v rtk &>/dev/null; then
      # Check if ~/.local/bin is already in shell profile
      local shell_rc="$HOME/.bashrc"
      if [ -n "${ZSH_VERSION:-}" ] || [ "$(basename "${SHELL:-}")" = "zsh" ]; then
        shell_rc="$HOME/.zshrc"
      fi
      if ! grep -q '\.local/bin' "$shell_rc" 2>/dev/null; then
        echo ""
        echo "  Note: add this to $shell_rc for permanent PATH access:"
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
      fi
      return 0
    fi
  fi

  echo "  Could not install RTK automatically."
  echo "  Install manually: https://github.com/rtk-ai/rtk#installation"
  return 1
}

_merge_global_deny_rules() {
  local settings_file="$HOME/.claude/settings.json"

  # Fast-path: already merged
  if [ -f "$settings_file" ] && grep -q 'Read(\*\*/node_modules/\*\*)' "$settings_file" 2>/dev/null; then
    echo "  Global deny rules already present — skipping."
    return 0
  fi

  mkdir -p "$HOME/.claude"

  # Build JSON array of deny rules
  local rules_json="["
  local first=true
  for rule in "${GLOBAL_DENY_RULES[@]}"; do
    if [ "$first" = true ]; then
      first=false
    else
      rules_json+=","
    fi
    rules_json+="\"$rule\""
  done
  rules_json+="]"

  if [ ! -f "$settings_file" ]; then
    # No existing file — create from scratch
    python3 -c "
import json, sys
rules = json.loads(sys.argv[1])
data = {'permissions': {'deny': rules}}
print(json.dumps(data, indent=2))
" "$rules_json" > "$settings_file" 2>/dev/null && {
      echo "  Created ~/.claude/settings.json with global deny rules."
      return 0
    }
    # python3 failed, try jq
    if command -v jq &>/dev/null; then
      echo "$rules_json" | jq '{permissions: {deny: .}}' > "$settings_file" 2>/dev/null && {
        echo "  Created ~/.claude/settings.json with global deny rules."
        return 0
      }
    fi
  else
    # Merge into existing file
    local merged
    merged=$(python3 -c "
import json, sys
rules = json.loads(sys.argv[1])
with open(sys.argv[2]) as f:
    data = json.load(f)
perms = data.setdefault('permissions', {})
existing = set(perms.get('deny', []))
perms['deny'] = perms.get('deny', []) + [r for r in rules if r not in existing]
print(json.dumps(data, indent=2))
" "$rules_json" "$settings_file" 2>/dev/null) && {
      echo "$merged" > "$settings_file"
      echo "  Merged global deny rules into ~/.claude/settings.json."
      return 0
    }
    # python3 failed, try jq
    if command -v jq &>/dev/null; then
      merged=$(jq --argjson rules "$rules_json" '
        .permissions //= {} |
        .permissions.deny //= [] |
        .permissions.deny = (.permissions.deny + ($rules - .permissions.deny))
      ' "$settings_file" 2>/dev/null) && {
        echo "$merged" > "$settings_file"
        echo "  Merged global deny rules into ~/.claude/settings.json."
        return 0
      }
    fi
  fi

  echo "  Warning: Could not merge deny rules (python3 and jq unavailable)."
  echo "  Add these rules manually to ~/.claude/settings.json:"
  echo "  https://github.com/nickmaglowsch/claude-setup#token-reducer-pack"
  return 1
}

_install_context_mode() {
  local claude_json="$HOME/.claude.json"

  # Check if already configured (claude mcp add writes to ~/.claude.json)
  if { [ -f "$claude_json" ] && grep -q '"context-mode"' "$claude_json" 2>/dev/null; } || \
     { [ -f "$HOME/.claude/settings.json" ] && grep -q '"context-mode"' "$HOME/.claude/settings.json" 2>/dev/null; }; then
    echo "  context-mode MCP server already configured — skipping."
    return 0
  fi

  # Check for npx — resolve full path so MCP startup works even if
  # Node is managed by mise/nvm/fnm and not on the default PATH.
  local npx_path
  npx_path=$(command -v npx 2>/dev/null) || {
    echo "  npx not found — install Node.js 18+ to use context-mode."
    echo "  Then add manually: https://github.com/mksglu/context-mode#installation"
    return 1
  }

  # Prefer `claude mcp add` (writes to the correct config location)
  if command -v claude &>/dev/null; then
    claude mcp add -s user context-mode -- "$npx_path" -y context-mode@latest 2>/dev/null && {
      echo "  Added context-mode MCP server via 'claude mcp add'."
      return 0
    }
  fi

  # Fallback: merge into ~/.claude.json directly
  local mcp_config="{\"type\":\"stdio\",\"command\":\"$npx_path\",\"args\":[\"-y\",\"context-mode@latest\"],\"env\":{}}"

  if [ ! -f "$claude_json" ]; then
    python3 -c "
import json, sys
config = json.loads(sys.argv[1])
data = {'mcpServers': {'context-mode': config}}
print(json.dumps(data, indent=2))
" "$mcp_config" > "$claude_json" 2>/dev/null && {
      echo "  Created ~/.claude.json with context-mode MCP server."
      return 0
    }
    if command -v jq &>/dev/null; then
      echo "$mcp_config" | jq '{mcpServers: {"context-mode": .}}' > "$claude_json" 2>/dev/null && {
        echo "  Created ~/.claude.json with context-mode MCP server."
        return 0
      }
    fi
  else
    local merged
    merged=$(python3 -c "
import json, sys
config = json.loads(sys.argv[1])
with open(sys.argv[2]) as f:
    data = json.load(f)
mcp = data.setdefault('mcpServers', {})
mcp['context-mode'] = config
print(json.dumps(data, indent=2))
" "$mcp_config" "$claude_json" 2>/dev/null) && {
      echo "$merged" > "$claude_json"
      echo "  Added context-mode MCP server to ~/.claude.json."
      return 0
    }
    if command -v jq &>/dev/null; then
      merged=$(jq --argjson config "$mcp_config" '
        .mcpServers //= {} |
        .mcpServers["context-mode"] = $config
      ' "$claude_json" 2>/dev/null) && {
        echo "$merged" > "$claude_json"
        echo "  Added context-mode MCP server to ~/.claude.json."
        return 0
      }
    fi
  fi

  echo "  Warning: Could not configure context-mode (claude CLI, python3, and jq unavailable)."
  echo "  Add manually: https://github.com/mksglu/context-mode#installation"
  return 1
}

_install_nudge_hook() {
  local hook_src="$SCRIPT_DIR/.claude/hooks/token-reducer-nudge.sh"
  local hook_dest="$HOME/.claude/hooks/token-reducer-nudge.sh"
  local settings_file="$HOME/.claude/settings.json"

  # Copy the nudge script
  mkdir -p "$HOME/.claude/hooks"
  if [ -f "$hook_src" ]; then
    cp "$hook_src" "$hook_dest"
    chmod +x "$hook_dest"
  fi

  # Register the UserPromptSubmit hook in settings.json
  if [ -f "$settings_file" ] && grep -q 'token-reducer-nudge' "$settings_file" 2>/dev/null; then
    return 0  # already registered
  fi

  mkdir -p "$HOME/.claude"

  if [ ! -f "$settings_file" ]; then
    # Create settings.json with just the hook
    cat > "$settings_file" <<'HOOK_EOF'
{
  "hooks": {
    "UserPromptSubmit": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "bash ~/.claude/hooks/token-reducer-nudge.sh"
          }
        ]
      }
    ]
  }
}
HOOK_EOF
  else
    # Merge hook into existing settings.json
    local merged
    merged=$(python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
hooks = data.setdefault('hooks', {})
ups = hooks.setdefault('UserPromptSubmit', [])
# Check if already registered
for entry in ups:
    for h in entry.get('hooks', []):
        if 'token-reducer-nudge' in h.get('command', ''):
            print(json.dumps(data, indent=2))
            sys.exit(0)
ups.append({
    'matcher': '',
    'hooks': [{'type': 'command', 'command': 'bash ~/.claude/hooks/token-reducer-nudge.sh'}]
})
print(json.dumps(data, indent=2))
" "$settings_file" 2>/dev/null) && {
      echo "$merged" > "$settings_file"
      return 0
    }
    # python3 failed, try jq
    if command -v jq &>/dev/null; then
      merged=$(jq '
        .hooks //= {} |
        .hooks.UserPromptSubmit //= [] |
        if (.hooks.UserPromptSubmit | map(.hooks[]?.command // "" | test("token-reducer-nudge")) | any)
        then .
        else .hooks.UserPromptSubmit += [{"matcher": "", "hooks": [{"type": "command", "command": "bash ~/.claude/hooks/token-reducer-nudge.sh"}]}]
        end
      ' "$settings_file" 2>/dev/null) && {
        echo "$merged" > "$settings_file"
        return 0
      }
    fi
  fi
}

_remove_nudge_hook() {
  # Remove the marker so it doesn't nudge, and clean up the hook
  touch "$HOME/.claude/.token-reducer-nudged"
}

# --- Status line: copy script and merge config into ~/.claude/settings.json ---
_install_statusline_config() {
  local script_dest="$HOME/.claude/statusline.sh"
  local settings_file="$HOME/.claude/settings.json"

  # The script itself is already copied via CLAUDE_FILES — just chmod it.
  if [ -f "$script_dest" ]; then
    chmod +x "$script_dest" 2>/dev/null || true
  fi

  mkdir -p "$HOME/.claude"

  # If statusLine is already configured (any value), don't clobber it.
  if [ -f "$settings_file" ] && grep -q '"statusLine"' "$settings_file" 2>/dev/null; then
    return 0
  fi

  local cfg='{"type":"command","command":"bash ~/.claude/statusline.sh","padding":0}'

  if [ ! -f "$settings_file" ]; then
    python3 -c "
import json, sys
cfg = json.loads(sys.argv[1])
print(json.dumps({'statusLine': cfg}, indent=2))
" "$cfg" > "$settings_file" 2>/dev/null && {
      echo "  Created ~/.claude/settings.json with statusLine config."
      return 0
    }
    if command -v jq &>/dev/null; then
      echo "$cfg" | jq '{statusLine: .}' > "$settings_file" 2>/dev/null && {
        echo "  Created ~/.claude/settings.json with statusLine config."
        return 0
      }
    fi
  else
    local merged
    merged=$(python3 -c "
import json, sys
cfg = json.loads(sys.argv[1])
with open(sys.argv[2]) as f:
    data = json.load(f)
data['statusLine'] = cfg
print(json.dumps(data, indent=2))
" "$cfg" "$settings_file" 2>/dev/null) && {
      echo "$merged" > "$settings_file"
      echo "  Added statusLine to ~/.claude/settings.json."
      return 0
    }
    if command -v jq &>/dev/null; then
      merged=$(jq --argjson cfg "$cfg" '.statusLine = $cfg' "$settings_file" 2>/dev/null) && {
        echo "$merged" > "$settings_file"
        echo "  Added statusLine to ~/.claude/settings.json."
        return 0
      }
    fi
  fi

  echo "  Warning: could not wire up statusLine (python3 and jq unavailable)."
  echo "  Add manually to ~/.claude/settings.json:"
  echo "    \"statusLine\": $cfg"
  return 1
}

_setup_token_reducer_pack() {
  echo "=== Token Reducer Pack ==="
  echo ""
  echo "  Three tiers of token reduction — each tier builds on the previous:"
  echo ""
  echo "  Tier 1 — Deny rules (always-on, zero overhead)"
  echo "    Blocks Claude from reading build artifacts, lock files, caches"
  echo ""
  echo "  Tier 2 — RTK (recommended)"
  echo "    Compresses Bash tool output (70-90% token savings on CLI noise)"
  echo ""
  echo "  Tier 3 — context-mode MCP server (power users)"
  echo "    Sandbox execution, FTS5 knowledge base, session continuity"
  echo "    Keeps raw data out of context — 98% reduction on large outputs"
  echo "    License: Elastic License v2 (source-available, not OSI open-source)"
  echo ""
  echo "  Options:"
  echo "    1) Tier 1 + 2  — deny rules + RTK (default)"
  echo "    2) Tier 1 only — deny rules"
  echo "    3) All tiers   — deny rules + RTK + context-mode"
  echo "    n) Skip"
  echo ""
  read -rp "  Choose [1/2/3/n]: " trp_choice
  echo ""

  if [[ "$trp_choice" =~ ^[Nn]$ ]]; then
    _install_nudge_hook
    return
  fi

  # Mark as installed so the nudge hook stays silent
  _remove_nudge_hook

  # --- Tier 1: Global deny rules (all choices except skip) ---
  _merge_global_deny_rules
  echo ""

  # --- Tier 2: RTK (choices 1 and 3, or default) ---
  if [[ "$trp_choice" != "2" ]]; then
    if command -v rtk &>/dev/null; then
      echo "  RTK already installed ($(rtk --version 2>/dev/null || echo 'unknown version'))."
      echo "  Refreshing Claude Code hook..."
      rtk init -g --auto-patch 2>&1 | sed 's/^/    /' || true
    else
      if _install_rtk; then
        echo "  Initializing RTK hook for Claude Code..."
        rtk init -g --auto-patch 2>&1 | sed 's/^/    /' || {
          echo "  Warning: rtk init failed. Run 'rtk init -g' manually after install."
        }
      fi
    fi
    echo ""
  fi

  # --- Tier 3: context-mode (choice 3 only) ---
  if [[ "$trp_choice" == "3" ]]; then
    _install_context_mode || true
    echo ""
  fi
}

# --- Global install: copy agents + skills into ~/.claude/ ---
perform_global_install() {
  # Save the original project directory; TARGET_DIR is swapped to $HOME during global install.
  local original_project_dir="$TARGET_DIR"
  TARGET_DIR="$HOME"
  local global_dir="$HOME/.claude"
  local is_update=false

  if [ -d "$global_dir/agents" ]; then
    is_update=true
  fi

  if [ "$is_update" = true ]; then
    echo "Updating Claude Code agents and skills globally in: $global_dir"
  else
    echo "Installing Claude Code agents and skills globally in: $global_dir"
  fi
  echo ""

  # Pull latest template
  if git -C "$SCRIPT_DIR" rev-parse --git-dir &>/dev/null; then
    echo "=== Pulling latest template ==="
    git -C "$SCRIPT_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
    echo ""
  fi

  if [ "$is_update" = true ]; then
    echo "=== Updating: agents and skills ==="
  else
    echo "=== Installing: agents and skills ==="
  fi
  echo ""

  for file in "${CLAUDE_FILES[@]}"; do
    if [ -f "$SCRIPT_DIR/$file" ]; then
      local dest="$HOME/$file"
      if [ "$is_update" = true ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$dest"
      else
        copy_file "$SCRIPT_DIR/$file" "$dest"
      fi
    fi
  done

  echo ""

  # --- Auto-update ---
  local autoupdate_script="$HOME/.claude/auto-update.sh"
  if [ -f "$SCRIPT_DIR/auto-update.sh" ]; then
    local cron_installed=false
    if crontab -l 2>/dev/null | grep -qF "auto-update.sh"; then
      cron_installed=true
    fi

    if [ -n "$AUTO_UPDATE_INTERVAL" ]; then
      # Explicit --interval flag: update interval and (re)install cron
      echo "=== Auto-updates ==="
      echo ""
      _install_auto_update
      echo ""
    elif [ "$cron_installed" = true ]; then
      # Already opted in — silently refresh the script (keep existing interval)
      echo "=== Refreshing: auto-update.sh ==="
      echo ""
      _install_auto_update
      echo ""
    else
      # Not yet opted in — ask and let user pick an interval
      echo "=== Auto-updates ==="
      echo ""
      echo "  Checks GitHub periodically and silently applies updates when"
      echo "  a new commit lands on main. Sends a system notification when done."
      echo "  Works on macOS, Linux, and WSL. Uses cron — no extra tools needed."
      echo ""
      read -rp "  Enable auto-updates? [y/N] " enable_auto
      echo ""
      if [[ "$enable_auto" =~ ^[Yy]$ ]]; then
        echo "  How often should it check? (examples: 5m, 30m, 1h, 6h, 1d)"
        while true; do
          read -rp "  Interval [5m]: " user_interval
          AUTO_UPDATE_INTERVAL="${user_interval:-5m}"
          if [ -n "$(_interval_to_cron "$AUTO_UPDATE_INTERVAL")" ]; then
            break
          fi
          echo "  Invalid interval. Examples: 5m, 30m, 1h, 6h, 1d"
        done
        _install_auto_update
        echo ""
      fi
    fi
  fi

  # --- Status line ---
  echo "=== Status line ==="
  echo ""
  _install_statusline_config
  echo ""

  # --- Token Reducer Pack ---
  _setup_token_reducer_pack

  TARGET_DIR="$original_project_dir"
  setup_compat_layer
  TARGET_DIR="$HOME"

  if [ "$is_update" = true ]; then
    echo "=== Global update complete! ==="
  else
    echo "=== Global install complete! ==="
  fi
  echo ""
  echo "  Agents and skills are now available globally across all your projects."
  echo "  Location: $global_dir"
  if [ -f "$autoupdate_script" ] && crontab -l 2>/dev/null | grep -qF "auto-update.sh"; then
    local current_interval
    current_interval=$(_get_auto_update_interval)
    echo "  Auto-updates: enabled (cron, $(_interval_label "$current_interval")) — log: ~/.claude/auto-update.log"
    echo "  To change interval: ./setup.sh --interval <value>  (e.g. 5m, 1h, 1d)"
    echo "  To disable: crontab -e  →  remove the line containing auto-update.sh"
  fi
  # Token Reducer summary
  local tr_parts=()
  if [ -f "$HOME/.claude/settings.json" ] && grep -q 'Read(\*\*/node_modules/\*\*)' "$HOME/.claude/settings.json" 2>/dev/null; then
    tr_parts+=("deny rules")
  fi
  if command -v rtk &>/dev/null; then
    tr_parts+=("RTK")
  fi
  if { [ -f "$HOME/.claude.json" ] && grep -q '"context-mode"' "$HOME/.claude.json" 2>/dev/null; } || \
     { [ -f "$HOME/.claude/settings.json" ] && grep -q '"context-mode"' "$HOME/.claude/settings.json" 2>/dev/null; }; then
    tr_parts+=("context-mode")
  fi
  if [ ${#tr_parts[@]} -gt 0 ]; then
    local IFS='+'
    echo "  Token Reducer: ${tr_parts[*]} active in ~/.claude/settings.json"
  fi
  echo ""
}

# Token reducer only: run just the token reducer pack and exit
if [ "$TOKEN_REDUCER_ONLY" = true ]; then
  _setup_token_reducer_pack
  exit 0
fi

# Global mode: install into ~/.claude/ and exit early (no git/project checks needed)
if [ "$GLOBAL_MODE" = true ]; then
  perform_global_install
  exit 0
fi

# ===========================================================================
# UPDATE MODE
# ===========================================================================
if [ "$UPDATE_MODE" = true ]; then
  # Verify target already has a Claude setup (relevant when --update is forced)
  if [ ! -d "$TARGET_DIR/.claude/agents" ]; then
    echo "Error: '$TARGET_DIR' does not have an existing Claude setup (.claude/agents/ not found)." >&2
    echo "Run without --update for first-time setup." >&2
    exit 1
  fi

  echo "Updating Claude Code setup in: $TARGET_DIR"
  echo ""

  # Pull latest template if this is a git repo
  if git -C "$SCRIPT_DIR" rev-parse --git-dir &>/dev/null; then
    echo "=== Pulling latest template ==="
    git -C "$SCRIPT_DIR" pull --ff-only 2>&1 | sed 's/^/  /'
    echo ""
  else
    echo "Warning: Template directory is not a git repo, using files as-is."
    echo ""
  fi

  # Update core .claude/ files (skip settings.local.json to preserve user config)
  echo "=== Updating: .claude/ agents, skills ==="
  echo ""

  for file in "${CLAUDE_FILES[@]}"; do
    if [ -f "$SCRIPT_DIR/$file" ]; then
      force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
    fi
  done

  echo ""

  # Update devcontainer if it already exists, or install it if --add-devcontainer was passed
  if [ -d "$TARGET_DIR/.devcontainer" ]; then
    echo "=== Updating: .devcontainer/ ==="
    echo ""

    for file in "${DEVCONTAINER_FILES[@]}"; do
      if [ -f "$SCRIPT_DIR/$file" ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
      fi
    done

    chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true
    echo ""
  elif [ "$ADD_DEVCONTAINER" = true ]; then
    echo "=== Adding: .devcontainer/ ==="
    echo ""

    for file in "${DEVCONTAINER_FILES[@]}"; do
      if [ -f "$SCRIPT_DIR/$file" ]; then
        force_copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
      fi
    done

    chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true
    echo ""
  fi

  # Update run-claude.sh if it already exists in target
  if [ -f "$TARGET_DIR/run-claude.sh" ]; then
    echo "=== Updating: run-claude.sh ==="
    echo ""
    force_copy_file "$SCRIPT_DIR/run-claude.sh" "$TARGET_DIR/run-claude.sh"
    chmod +x "$TARGET_DIR/run-claude.sh" 2>/dev/null || true
    echo ""
  fi

  # Install playwright-cli if qa-agent is installed and not already present
  if command -v playwright-cli &>/dev/null; then
    echo "=== playwright-cli already installed — skipping ==="
    echo ""
  else
    echo "=== playwright-cli (for /qa browser testing) ==="
    echo ""
    read -rp "  Install playwright-cli for browser-based QA (/qa skill)? [y/N] " install_playwright
    echo ""
    if [[ "$install_playwright" =~ ^[Yy]$ ]]; then
      if command -v npm &>/dev/null; then
        npm install -g @playwright/cli
        playwright-cli install
        playwright-cli install --skills
      else
        echo "  npm not found — install playwright-cli manually: npm install -g @playwright/cli"
      fi
      echo ""
    fi
  fi

  # --- Token Reducer Pack (silent refresh on update) ---
  echo "=== Refreshing: Token Reducer Pack ==="
  echo ""
  _merge_global_deny_rules
  if command -v rtk &>/dev/null; then
    echo "  RTK installed — refreshing hook..."
    rtk init -g --auto-patch 2>&1 | sed 's/^/    /' || true
  fi
  # Refresh context-mode config if already present
  if { [ -f "$HOME/.claude.json" ] && grep -q '"context-mode"' "$HOME/.claude.json" 2>/dev/null; } || \
     { [ -f "$HOME/.claude/settings.json" ] && grep -q '"context-mode"' "$HOME/.claude/settings.json" 2>/dev/null; }; then
    echo "  context-mode MCP server already configured — skipping."
  fi
  echo ""

  # Ensure .gitignore has required entries
  echo "=== Updating .gitignore ==="
  echo ""

  GITIGNORE_ENTRIES=(
    ".devcontainer/.env"
    ".claude/settings.local.json"
    ".claude/auth.local.md"
    ".claude-worktrees/"
    ".DS_Store"
    "tasks/**"
    "qa-output/**"
    "debug-output/"
    ".playwright-cli/"
  )

  GITIGNORE_FILE="$TARGET_DIR/.gitignore"
  touch "$GITIGNORE_FILE"

  # Ensure file ends with a newline before appending
  if [ -s "$GITIGNORE_FILE" ] && [ "$(tail -c1 "$GITIGNORE_FILE" | wc -l)" -eq 0 ]; then
    echo "" >> "$GITIGNORE_FILE"
  fi

  # Add section comment if any entries are missing and comment doesn't exist yet
  NEEDS_SECTION=false
  for entry in "${GITIGNORE_ENTRIES[@]}"; do
    if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
      NEEDS_SECTION=true
      break
    fi
  done
  if [ "$NEEDS_SECTION" = true ] && ! grep -qxF "# .claude" "$GITIGNORE_FILE" 2>/dev/null; then
    echo "# .claude" >> "$GITIGNORE_FILE"
  fi

  for entry in "${GITIGNORE_ENTRIES[@]}"; do
    if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
      echo "$entry" >> "$GITIGNORE_FILE"
      echo "  Added to .gitignore: $entry"
    fi
  done

  echo ""

  setup_compat_layer

  echo "=== Update complete! ==="
  echo ""
  echo "  Updated template files. Your settings.local.json and agent-memory/ were preserved."
  echo "  Review the changes with: cd $TARGET_DIR && git diff"
  echo ""
  exit 0
fi

# ===========================================================================
# FIRST-TIME SETUP (original behavior)
# ===========================================================================
echo "Setting up Claude Code in: $TARGET_DIR"
echo ""

# --- Step 1: Core .claude/ files (always) ---
echo "=== Core: .claude/ agents, skills, settings ==="
echo ""

for file in "${CLAUDE_FILES[@]}"; do
  copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
done

# Create default settings.local.json if it doesn't exist
SETTINGS_FILE="$TARGET_DIR/.claude/settings.local.json"
if [ ! -f "$SETTINGS_FILE" ]; then
  mkdir -p "$TARGET_DIR/.claude"
  cat > "$SETTINGS_FILE" <<'SETTINGS_EOF'
{
  "permissions": {
    "allow": [],
    "deny": []
  }
}
SETTINGS_EOF
  echo "  Created: .claude/settings.local.json (add your permission rules here)"
else
  echo "  Kept existing: .claude/settings.local.json"
fi

echo ""

# --- Step 2: Dev container (optional) ---
read -rp "Do you want dev container support? [y/N] " install_devcontainer
echo ""

if [[ "$install_devcontainer" =~ ^[Yy]$ ]]; then
  echo "=== Dev Container: .devcontainer/ ==="
  echo ""

  for file in "${DEVCONTAINER_FILES[@]}"; do
    copy_file "$SCRIPT_DIR/$file" "$TARGET_DIR/$file"
  done

  # Make firewall script executable
  chmod +x "$TARGET_DIR/.devcontainer/init-firewall.sh" "$TARGET_DIR/.devcontainer/fix-git-worktree.sh" 2>/dev/null || true

  echo ""

  # --- Step 3: Headless runner (optional, only if devcontainer selected) ---
  read -rp "Include headless runner script (run-claude.sh)? [y/N] " install_runner
  echo ""

  if [[ "$install_runner" =~ ^[Yy]$ ]]; then
    echo "=== Headless Runner: run-claude.sh ==="
    echo ""
    copy_file "$SCRIPT_DIR/run-claude.sh" "$TARGET_DIR/run-claude.sh"
    chmod +x "$TARGET_DIR/run-claude.sh" 2>/dev/null || true
    echo ""
  fi
fi

# --- Step 3b: playwright-cli (optional) ---
if command -v playwright-cli &>/dev/null; then
  echo "=== playwright-cli already installed — skipping ==="
  echo ""
else
  echo "=== playwright-cli (for /qa browser testing) ==="
  echo ""
  read -rp "Install playwright-cli for browser-based QA (/qa skill)? [y/N] " install_playwright
  echo ""
  if [[ "$install_playwright" =~ ^[Yy]$ ]]; then
    if command -v npm &>/dev/null; then
      npm install -g @playwright/cli
      playwright-cli install
      playwright-cli install --skills
    else
      echo "  npm not found — install playwright-cli manually: npm install -g @playwright/cli"
    fi
    echo ""
  fi
fi

# --- Step 3c: Token Reducer Pack (optional) ---
_setup_token_reducer_pack

# --- Step 4: Update .gitignore ---
echo "=== Updating .gitignore ==="
echo ""

GITIGNORE_ENTRIES=(
  ".devcontainer/.env"
  ".claude/settings.local.json"
  ".claude/auth.local.md"
  ".claude-worktrees/"
  ".DS_Store"
  "tasks/**"
  "qa-output/**"
  "debug-output/"
  ".playwright-cli/"
)

GITIGNORE_FILE="$TARGET_DIR/.gitignore"
touch "$GITIGNORE_FILE"

# Ensure file ends with a newline before appending
if [ -s "$GITIGNORE_FILE" ] && [ "$(tail -c1 "$GITIGNORE_FILE" | wc -l)" -eq 0 ]; then
  echo "" >> "$GITIGNORE_FILE"
fi

# Add section comment if any entries are missing and comment doesn't exist yet
NEEDS_SECTION=false
for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
    NEEDS_SECTION=true
    break
  fi
done
if [ "$NEEDS_SECTION" = true ] && ! grep -qxF "# .claude" "$GITIGNORE_FILE" 2>/dev/null; then
  echo "# .claude" >> "$GITIGNORE_FILE"
fi

for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qxF "$entry" "$GITIGNORE_FILE" 2>/dev/null; then
    echo "$entry" >> "$GITIGNORE_FILE"
    echo "  Added to .gitignore: $entry"
  else
    echo "  Already in .gitignore: $entry"
  fi
done

echo ""

# --- Step 5: Compatibility symlinks (optional, via --compatible flag) ---
setup_compat_layer

# --- Done ---
echo "=== Setup complete! ==="
echo ""
echo "Next steps:"
echo "  1. Authenticate:      claude login  (uses your Max/Pro subscription)"
echo "  2. Review .claude/settings.local.json and adjust permissions"
echo "  3. Run Claude Code:   claude"
echo ""
if [[ "${install_devcontainer:-}" =~ ^[Yy]$ ]]; then
  echo "  Dev container:"
  echo "    - VS Code: open the project, then 'Reopen in Container'"
  echo "    - Zed: open the project, you'll be prompted to launch in a container"
  echo "    - Run 'claude login' inside the container to authenticate"
  echo "    - See .devcontainer/README.md for full documentation"
  echo ""
fi
if [[ "${install_runner:-}" =~ ^[Yy]$ ]]; then
  echo "  Headless mode:"
  echo "    ./run-claude.sh --branch feature-x --prompt 'implement the feature'"
  echo ""
fi
if [[ "${install_playwright:-}" =~ ^[Yy]$ ]]; then
  echo "  Browser QA:"
  echo "    Run /qa in Claude Code with your app running to test it like a user"
  echo "    playwright-cli is installed and ready — no extra config needed"
  echo ""
fi
# Token Reducer summary
tr_parts=()
if [ -f "$HOME/.claude/settings.json" ] && grep -q 'Read(\*\*/node_modules/\*\*)' "$HOME/.claude/settings.json" 2>/dev/null; then
  tr_parts+=("deny rules")
fi
if command -v rtk &>/dev/null; then
  tr_parts+=("RTK")
fi
if { [ -f "$HOME/.claude.json" ] && grep -q '"context-mode"' "$HOME/.claude.json" 2>/dev/null; } || \
   { [ -f "$HOME/.claude/settings.json" ] && grep -q '"context-mode"' "$HOME/.claude/settings.json" 2>/dev/null; }; then
  tr_parts+=("context-mode")
fi
if [ ${#tr_parts[@]} -gt 0 ]; then
  echo "  Token Reducer: $(IFS='+'; echo "${tr_parts[*]}") active in ~/.claude/settings.json"
  echo ""
fi
